Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2018-03, with the labels that each got.

#773 Fix capped crowdsale flaky test
  test/crowdsale/CappedCrowdsale.test.js
Labels: bug, review

#789 Bugfix/fix individuallycapped flaky test
  test/crowdsale/IndividuallyCappedCrowdsale.test.js
Labels: bug, review

#772 Move ERC20 tests to ERC20 custom folder
  test/token/ERC20/BasicToken.test.js
  test/token/ERC20/BurnableToken.test.js
  test/token/ERC20/CappedToken.test.js
  test/token/ERC20/MintableToken.test.js
  test/token/ERC20/PausableToken.test.js
  test/token/ERC20/StandardToken.test.js
  test/token/ERC20/TokenTimelock.test.js
  test/token/ERC20/TokenVesting.test.js
Labels: enhancement, review

#803 ERC721 full implementation
  contracts/AddressUtils.sol
  contracts/mocks/ERC721BasicTokenMock.sol
  contracts/mocks/ERC721ReceiverMock.sol
  contracts/mocks/ERC721TokenMock.sol
  contracts/token/ERC721/DeprecatedERC721.sol
  contracts/token/ERC721/ERC721.sol
  contracts/token/ERC721/ERC721Basic.sol
  contracts/token/ERC721/ERC721BasicToken.sol
  contracts/token/ERC721/ERC721Holder.sol
  contracts/token/ERC721/ERC721Receiver.sol
  contracts/token/ERC721/ERC721Token.sol
  test/helpers/sendTransaction.js
  test/token/ERC721/ERC721BasicToken.behaviour.js
  test/token/ERC721/ERC721BasicToken.test.js
  test/token/ERC721/ERC721MintBurn.behaviour.js
  test/token/ERC721/ERC721Token.test.js
Labels: review
