Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2018-07, with the labels that each got.

#1101 Improved documentation for _preValidatePurchase method in Crowdsale
  contracts/crowdsale/Crowdsale.sol
Labels: area:documentation, kind:improvement

#1107 Remove payable from Destructible constructor
  contracts/lifecycle/Destructible.sol
  contracts/mocks/DestructibleMock.sol
  test/lifecycle/Destructible.test.js
Labels: area:contracts, breaking change, bug, kind:improvement

#1114 fix: move RBAC to //access
  contracts/access/SignatureBouncer.sol
  contracts/access/Whitelist.sol
  contracts/access/rbac/RBAC.sol
  contracts/access/rbac/Roles.sol
  contracts/examples/RBACWithAdmin.sol
  contracts/ownership/Superuser.sol
  contracts/token/ERC20/RBACMintableToken.sol
Labels: area:contracts, kind:improvement

#1112 fix: bounty tests, superceeds #799
  test/Bounty.test.js
Labels: area:tests, bug, kind:improvement

#1117 Prefer const in test files
  .eslintrc
  test/AutoIncrementing.test.js
  test/Bounty.test.js
  test/LimitBalance.test.js
  test/ReentrancyGuard.test.js
  test/crowdsale/AllowanceCrowdsale.test.js
  test/crowdsale/CappedCrowdsale.test.js
  test/crowdsale/Crowdsale.test.js
  test/crowdsale/IndividuallyCappedCrowdsale.test.js
  test/crowdsale/MintedCrowdsale.behaviour.js
  test/crowdsale/WhitelistedCrowdsale.test.js
  test/helpers/increaseTime.js
  test/helpers/sendTransaction.js
  test/helpers/sign.js
  test/helpers/transactionMined.js
  test/introspection/SupportsInterface.behavior.js
  test/library/ECRecovery.test.js
  test/library/Math.test.js
  test/library/MerkleProof.test.js
  test/lifecycle/Destructible.test.js
  test/lifecycle/Pausable.test.js
  test/lifecycle/TokenDestructible.test.js
  test/ownership/Claimable.test.js
  test/ownership/Contactable.test.js
  test/ownership/DelayedClaimable.test.js
  test/ownership/HasNoEther.test.js
  test/ownership/Ownable.behaviour.js
  test/ownership/Whitelist.test.js
  test/payment/RefundEscrow.test.js
  test/token/ERC20/CappedToken.behaviour.js
  test/token/ERC20/CappedToken.test.js
Labels: area:tests, kind:improvement

#1089 Added more comprehensive usage information to the Getting Started guide
  README.md
Labels: area:documentation, kind:improvement

#1119 Add EditorConfig
  .editorconfig
  .eslintrc
  test/Bounty.test.js
Labels: kind:improvement

#759 Making visibility explicit for storage variables
  contracts/token/ERC20/BasicToken.sol
Labels: next

#1057 Refactor/reentrancy guard gas optimization #1056
  contracts/ReentrancyGuard.sol
Labels: area:contracts, kind:improvement
