Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2018-11, with the labels that each got.

#1481 The beneficiary parameter of claimRefund is replaced with refundee
  contracts/crowdsale/distribution/RefundableCrowdsale.sol
Labels: area:contracts, kind:improvement

#1409 Remove redundant require statements
  contracts/token/ERC20/ERC20.sol
Labels: area:contracts, kind:improvement

#1507 Renamed roles private variables to adhere to code style.
  contracts/access/roles/CapperRole.sol
  contracts/access/roles/MinterRole.sol
  contracts/access/roles/PauserRole.sol
  contracts/access/roles/SignerRole.sol
Labels: area:contracts, kind:improvement

#1514 balanceDifference tests and application
  test/crowdsale/AllowanceCrowdsale.test.js
  test/crowdsale/Crowdsale.test.js
  test/crowdsale/MintedCrowdsale.behavior.js
  test/crowdsale/RefundableCrowdsale.test.js
  test/examples/SampleCrowdsale.test.js
  test/helpers/balanceDifference.js
  test/helpers/test/balanceDifference.test.js
  test/payment/PullPayment.test.js
  test/payment/escrow/Escrow.behavior.js
  test/payment/escrow/RefundEscrow.test.js
Labels: area:tests, kind:improvement

#1513 ether and shouldFail tests
  contracts/mocks/Failer.sol
  test/helpers/shouldFail.js
  test/helpers/test/ether.test.js
  test/helpers/test/shouldFail.test.js
Labels: area:tests, kind:feature

#1511 Now testing events in constructors!
  contracts/mocks/EventEmitter.sol
  package-lock.json
  package.json
  test/access/roles/PublicRole.behavior.js
  test/examples/SimpleToken.test.js
  test/helpers/decodeLogs.js
  test/helpers/expectEvent.js
  test/helpers/test/expectEvent.test.js
  test/token/ERC721/ERC721.behavior.js
Labels: area:tests, kind:feature

#1521 Added time helper tests.
  test/helpers/test/time.test.js
  test/helpers/time.js
Labels: area:tests, kind:improvement

#1524 Approval events on transferFrom and burnFrom
  contracts/token/ERC20/ERC20.sol
  test/token/ERC20/ERC20.test.js
Labels: area:contracts, kind:feature

#1523 Moved advanceBlock to time.
  test/crowdsale/FinalizableCrowdsale.test.js
  test/crowdsale/IncreasingPriceCrowdsale.test.js
  test/crowdsale/PostDeliveryCrowdsale.test.js
  test/crowdsale/RefundableCrowdsale.test.js
  test/crowdsale/TimedCrowdsale.test.js
  test/examples/SampleCrowdsale.test.js
  test/helpers/advanceToBlock.js
  test/helpers/test/advanceToBlock.test.js
  test/helpers/test/time.test.js
  test/helpers/time.js
Labels: area:tests, kind:improvement

#1527 Deleted transactionMined (unused).
  test/helpers/transactionMined.js
Labels: area:tests

#1530 Added makeInterfaceId tests.
  contracts/mocks/OwnableInterfaceId.sol
  test/helpers/test/makeInterfaceId.test.js
Labels: area:tests, kind:improvement
