Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2018-08, with the labels that each got.

#1105 Update Truffle and Solium
  contracts/access/SignatureBouncer.sol
  contracts/access/Whitelist.sol
  contracts/access/rbac/RBAC.sol
  contracts/access/rbac/Roles.sol
  contracts/crowdsale/distribution/FinalizableCrowdsale.sol
  contracts/crowdsale/validation/WhitelistedCrowdsale.sol
  contracts/examples/RBACWithAdmin.sol
  contracts/lifecycle/Destructible.sol
  contracts/lifecycle/Pausable.sol
  contracts/lifecycle/TokenDestructible.sol
  contracts/mocks/BouncerMock.sol
  contracts/mocks/DestructibleMock.sol
  contracts/mocks/ERC20WithMetadataMock.sol
  contracts/mocks/RBACCappedTokenMock.sol
  contracts/mocks/RBACMock.sol
  contracts/mocks/WhitelistMock.sol
  contracts/ownership/Claimable.sol
  contracts/ownership/Contactable.sol
  contracts/ownership/DelayedClaimable.sol
  contracts/ownership/HasNoTokens.sol
  contracts/proposals/ERC1046/TokenMetadata.sol
  contracts/token/ERC20/MintableToken.sol
  contracts/token/ERC20/RBACMintableToken.sol
  contracts/token/ERC20/SafeERC20.sol
  contracts/token/ERC721/ERC721Token.sol
  package-lock.json
  package.json
  test/ownership/HasNoEther.test.js
Labels: area:automation, kind:improvement

#1138 Disable Solium's error-reason rule
  .soliumrc.json
Labels: area:contracts, kind:improvement

#1141 Add an initial document for our code style
  CODE_STYLE.md
Labels: area:documentation, kind:improvement

#1140 Add an initial document for our release process
  RELEASING.md
Labels: area:documentation, kind:feature

#1142 Remove abbreviations from parameters
  CODE_STYLE.md
  contracts/AddressUtils.sol
  contracts/ECRecovery.sol
  contracts/access/SignatureBouncer.sol
  contracts/access/rbac/Roles.sol
  contracts/examples/RBACWithAdmin.sol
  contracts/mocks/BouncerMock.sol
  contracts/mocks/ECRecoveryMock.sol
  contracts/mocks/RBACMock.sol
  contracts/ownership/Superuser.sol
Labels: area:contracts, kind:improvement

#1137 All tests now use account names, and dont use accounts[0] (except ERC…
  test/Heritable.test.js
  test/LimitBalance.test.js
  test/ReentrancyGuard.test.js
  test/SimpleSavingsWallet.test.js
  test/examples/SampleCrowdsale.test.js
  test/examples/SimpleToken.test.js
  test/introspection/SupportsInterfaceWithLookup.test.js
  test/library/ECRecovery.test.js
  test/library/Math.test.js
  test/library/MerkleProof.test.js
  test/lifecycle/Destructible.test.js
  test/lifecycle/Pausable.test.js
  test/lifecycle/TokenDestructible.test.js
  test/ownership/CanReclaimToken.test.js
  test/ownership/Claimable.test.js
  test/ownership/Contactable.test.js
  test/ownership/DelayedClaimable.test.js
  test/ownership/HasNoContracts.test.js
  test/ownership/HasNoEther.test.js
  test/ownership/HasNoTokens.test.js
  test/ownership/Ownable.behaviour.js
  test/ownership/Ownable.test.js
  test/ownership/Superuser.test.js
  test/ownership/Whitelist.test.js
  test/ownership/rbac/RBAC.test.js
  test/payment/ConditionalEscrow.test.js
  test/payment/Escrow.test.js
  test/payment/PullPayment.test.js
  test/payment/RefundEscrow.test.js
  test/payment/SplitPayment.test.js
  test/token/ERC20/BurnableToken.behaviour.js
  test/token/ERC20/BurnableToken.test.js
  test/token/ERC20/CappedToken.behaviour.js
  test/token/ERC20/CappedToken.test.js
  test/token/ERC20/DetailedERC20.test.js
  test/token/ERC20/MintableToken.behaviour.js
  test/token/ERC20/MintableToken.test.js
  test/token/ERC20/RBACCappedToken.test.js
  test/token/ERC20/RBACMintableToken.behaviour.js
  test/token/ERC20/RBACMintableToken.test.js
  test/token/ERC20/StandardBurnableToken.test.js
Labels: area:tests, kind:improvement

#1128 Crowdsale inheritance order
  contracts/crowdsale/distribution/FinalizableCrowdsale.sol
  contracts/crowdsale/validation/IndividuallyCappedCrowdsale.sol
Labels: area:contracts, bug, kind:improvement

#1125 Consolidated ERC20 Interface and Implementation Files
  contracts/crowdsale/emission/AllowanceCrowdsale.sol
  contracts/lifecycle/TokenDestructible.sol
  contracts/mocks/BasicTokenMock.sol
  contracts/mocks/ERC223TokenMock.sol
  contracts/mocks/StandardBurnableTokenMock.sol
  contracts/ownership/CanReclaimToken.sol
  contracts/ownership/HasNoTokens.sol
  contracts/token/ERC20/BasicToken.sol
  contracts/token/ERC20/BurnableToken.sol
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC20/ERC20Basic.sol
  contracts/token/ERC20/SafeERC20.sol
  contracts/token/ERC20/StandardBurnableToken.sol
  contracts/token/ERC20/StandardToken.sol
  contracts/token/ERC20/TokenTimelock.sol
  contracts/token/ERC20/TokenVesting.sol
  test/ownership/CanReclaimToken.test.js
  test/token/ERC20/BasicToken.test.js
  test/token/ERC20/BurnableToken.behaviour.js
  test/token/ERC20/BurnableToken.test.js
  test/token/ERC20/StandardBurnableToken.test.js
  test/token/ERC20/StandardToken.test.js
Labels: area:contracts, breaking change, kind:improvement

#1149 Fixed HasNoTokens test.
  test/ownership/HasNoTokens.test.js
Labels: area:tests, kind:improvement

#1151 Renamed behaviour to behavior
  test/ReentrancyGuard.test.js
  test/crowdsale/MintedCrowdsale.behavior.js
  test/crowdsale/MintedCrowdsale.test.js
  test/ownership/Ownable.behavior.js
  test/ownership/Ownable.test.js
  test/payment/ConditionalEscrow.test.js
  test/payment/Escrow.behavior.js
  test/payment/Escrow.test.js
  test/token/ERC20/BurnableToken.behavior.js
  test/token/ERC20/BurnableToken.test.js
  test/token/ERC20/CappedToken.behavior.js
  test/token/ERC20/CappedToken.test.js
  test/token/ERC20/MintableToken.behavior.js
  test/token/ERC20/MintableToken.test.js
  test/token/ERC20/RBACCappedToken.test.js
  test/token/ERC20/RBACMintableToken.behavior.js
  test/token/ERC20/RBACMintableToken.test.js
  test/token/ERC721/ERC721BasicToken.behavior.js
  test/token/ERC721/ERC721BasicToken.test.js
  test/token/ERC721/ERC721MintBurn.behavior.js
  test/token/ERC721/ERC721Token.test.js
Labels: kind:improvement

#1156 Remove Math.min64 and Math.max64
  contracts/math/Math.sol
  contracts/mocks/MathMock.sol
  test/library/Math.test.js
Labels: area:contracts, breaking change, kind:improvement

#1160 Change `uint` to `uint256`
  contracts/mocks/BurnableTokenMock.sol
Labels: area:tests, kind:improvement

#1153 Add note about next tag in releasing document
  RELEASING.md
Labels: area:documentation, kind:improvement

#1161 Deploy the contract with the designated owner
  test/ownership/Claimable.test.js
Labels: area:contracts, bug, kind:improvement

#1169 inLogs no longer returns a promise.
  test/Bounty.test.js
  test/helpers/expectEvent.js
  test/payment/Escrow.behavior.js
  test/payment/RefundEscrow.test.js
  test/token/ERC20/BurnableToken.behavior.js
Labels: area:tests, kind:improvement

#1173 Change author to OpenZeppelin Community
  ethpm.json
  package.json
Labels: kind:improvement

#1187 feat: use require in SafeMath
  contracts/math/SafeMath.sol
  test/math/SafeMath.test.js
Labels: area:contracts, breaking change, kind:improvement

#1183 Replace all asserts with chai.should
  test/AutoIncrementing.test.js
  test/Bounty.test.js
  test/Heritable.test.js
  test/LimitBalance.test.js
  test/ReentrancyGuard.test.js
  test/SimpleSavingsWallet.test.js
  test/access/SignatureBouncer.test.js
  test/crowdsale/AllowanceCrowdsale.test.js
  test/crowdsale/CappedCrowdsale.test.js
  test/crowdsale/Crowdsale.test.js
  test/crowdsale/MintedCrowdsale.behavior.js
  test/crowdsale/MintedCrowdsale.test.js
  test/crowdsale/TimedCrowdsale.test.js
  test/crowdsale/WhitelistedCrowdsale.test.js
  test/examples/SimpleToken.test.js
  test/helpers/assertJump.js
  test/helpers/assertRevert.js
  test/helpers/expectThrow.js
  test/library/ECRecovery.test.js
  test/library/Math.test.js
  test/library/MerkleProof.test.js
  test/lifecycle/Destructible.test.js
  test/lifecycle/Pausable.test.js
  test/lifecycle/TokenDestructible.test.js
  test/ownership/CanReclaimToken.test.js
  test/ownership/Claimable.test.js
  test/ownership/Contactable.test.js
  test/ownership/DelayedClaimable.test.js
  test/ownership/HasNoContracts.test.js
  test/ownership/HasNoEther.test.js
  test/ownership/HasNoTokens.test.js
  test/payment/PullPayment.test.js
  test/payment/SplitPayment.test.js
  test/token/ERC20/CappedToken.behavior.js
  test/token/ERC20/MintableToken.behavior.js
  test/token/ERC20/PausableToken.test.js
  test/token/ERC20/RBACMintableToken.behavior.js
  test/token/ERC20/StandardToken.test.js
  test/token/ERC20/TokenVesting.test.js
  test/token/ERC721/ERC721BasicToken.behavior.js
  test/token/ERC721/ERC721MintBurn.behavior.js
Labels: area:tests, kind:improvement

#1188 Changed SplitPayment require to assert.
  contracts/payment/SplitPayment.sol
Labels: area:contracts, breaking change, kind:improvement

#1198 Change DOS line endings to Unix
  test/token/ERC20/CappedToken.behavior.js
  test/token/ERC20/RBACCappedToken.test.js
  test/token/ERC20/RBACMintableToken.behavior.js
Labels: kind:improvement

#1199 Switch to container-based Travis run
  .travis.yml
Labels: area:automation, kind:improvement

#1193 Make ERC721.exists internal
  contracts/mocks/ERC721TokenMock.sol
  contracts/token/ERC721/ERC721Basic.sol
  contracts/token/ERC721/ERC721BasicToken.sol
  contracts/token/ERC721/ERC721Token.sol
  test/token/ERC721/ERC721BasicToken.behavior.js
  test/token/ERC721/ERC721Token.test.js
Labels: area:contracts, breaking change, kind:improvement

#915 Add Modulo operation for getting the quotient
  contracts/math/SafeMath.sol
  contracts/mocks/SafeMathMock.sol
  test/math/SafeMath.test.js
Labels: area:contracts, kind:feature

#1170 Math.average
  contracts/math/Math.sol
  contracts/mocks/MathMock.sol
  test/library/Math.test.js
Labels: area:contracts, kind:feature

#1195 Increase testing coverage
  contracts/access/SignatureBouncer.sol
  contracts/token/ERC721/ERC721BasicToken.sol
  test/Bounty.test.js
  test/crowdsale/Crowdsale.test.js
  test/ownership/Superuser.test.js
  test/payment/RefundEscrow.test.js
  test/payment/SplitPayment.test.js
  test/token/ERC20/CappedToken.test.js
  test/token/ERC20/TokenTimelock.test.js
  test/token/ERC20/TokenVesting.test.js
  test/token/ERC721/ERC721Token.test.js
Labels: area:tests, breaking change, kind:improvement

#1197 StandardToken encapsulation
  contracts/examples/SimpleToken.sol
  contracts/mocks/BurnableTokenMock.sol
  contracts/mocks/ERC223TokenMock.sol
  contracts/mocks/PausableTokenMock.sol
  contracts/mocks/StandardTokenMock.sol
  contracts/token/ERC20/BurnableToken.sol
  contracts/token/ERC20/CappedToken.sol
  contracts/token/ERC20/MintableToken.sol
  contracts/token/ERC20/StandardToken.sol
  test/token/ERC20/CappedToken.behavior.js
  test/token/ERC20/MintableToken.behavior.js
  test/token/ERC20/StandardToken.test.js
Labels: area:contracts, breaking change, kind:feature, kind:improvement

#1213 Enforce linebreak style
  .eslintrc
  .soliumrc.json
Labels: kind:improvement

#967 tests: use stages for the travis execution
  .travis.yml
  package.json
  scripts/test.sh
Labels: area:automation, kind:improvement, status:in-progress

#1216 No longer assigning awaits to temporary variables.
  test/crowdsale/AllowanceCrowdsale.test.js
  test/crowdsale/CappedCrowdsale.test.js
  test/crowdsale/Crowdsale.test.js
  test/crowdsale/IncreasingPriceCrowdsale.test.js
  test/crowdsale/IndividuallyCappedCrowdsale.test.js
  test/crowdsale/MintedCrowdsale.behavior.js
  test/crowdsale/MintedCrowdsale.test.js
  test/crowdsale/PostDeliveryCrowdsale.test.js
  test/crowdsale/TimedCrowdsale.test.js
  test/crowdsale/WhitelistedCrowdsale.test.js
  test/examples/SampleCrowdsale.test.js
  test/examples/SimpleToken.test.js
  test/introspection/SupportsInterface.behavior.js
  test/library/ECRecovery.test.js
  test/library/Math.test.js
  test/library/MerkleProof.test.js
  test/lifecycle/Pausable.test.js
  test/lifecycle/TokenDestructible.test.js
  test/math/SafeMath.test.js
  test/ownership/CanReclaimToken.test.js
  test/ownership/Claimable.test.js
  test/ownership/Contactable.test.js
  test/ownership/DelayedClaimable.test.js
  test/ownership/HasNoEther.test.js
  test/ownership/HasNoTokens.test.js
  test/ownership/Superuser.test.js
  test/ownership/Whitelist.test.js
  test/payment/Escrow.behavior.js
  test/payment/PullPayment.test.js
  test/payment/RefundEscrow.test.js
  test/payment/SplitPayment.test.js
  test/proposals/ERC1046/TokenMetadata.test.js
  test/token/ERC20/BurnableToken.behavior.js
  test/token/ERC20/DetailedERC20.test.js
  test/token/ERC20/MintableToken.behavior.js
  test/token/ERC20/PausableToken.test.js
  test/token/ERC20/RBACMintableToken.behavior.js
  test/token/ERC20/StandardToken.test.js
  test/token/ERC20/TokenTimelock.test.js
  test/token/ERC20/TokenVesting.test.js
  test/token/ERC721/ERC721BasicToken.behavior.js
  test/token/ERC721/ERC721MintBurn.behavior.js
  test/token/ERC721/ERC721Token.test.js
Labels: area:tests, kind:improvement

#1218 Fix balance and allowance checks in _burn and _burnFrom
  contracts/token/ERC20/StandardToken.sol
  test/token/ERC20/StandardToken.test.js
Labels: area:contracts, bug, kind:improvement

#1225 remove arrow functions from js tests
  test/access/SignatureBouncer.test.js
  test/library/ECRecovery.test.js
  test/math/SafeMath.test.js
  test/ownership/HasNoContracts.test.js
  test/ownership/HasNoTokens.test.js
  test/ownership/Superuser.test.js
  test/ownership/rbac/RBAC.test.js
Labels: area:tests, kind:improvement

#1219 Minor test style improvements
  README.md
  test/.eslintrc
  test/Bounty.test.js
  test/Heritable.test.js
  test/access/SignatureBouncer.test.js
  test/crowdsale/AllowanceCrowdsale.test.js
  test/crowdsale/CappedCrowdsale.test.js
  test/crowdsale/Crowdsale.test.js
  test/crowdsale/MintedCrowdsale.behavior.js
  test/crowdsale/MintedCrowdsale.test.js
  test/crowdsale/TimedCrowdsale.test.js
  test/crowdsale/WhitelistedCrowdsale.test.js
  test/examples/SampleCrowdsale.test.js
  test/examples/SimpleToken.test.js
  test/helpers/expectEvent.js
  test/introspection/SupportsInterface.behavior.js
  test/library/ECRecovery.test.js
  test/library/MerkleProof.test.js
  test/lifecycle/Pausable.test.js
  test/ownership/Claimable.test.js
  test/ownership/Contactable.test.js
  test/ownership/DelayedClaimable.test.js
  test/ownership/HasNoContracts.test.js
  test/ownership/Ownable.behavior.js
  test/ownership/Superuser.test.js
  test/ownership/Whitelist.test.js
  test/payment/SplitPayment.test.js
  test/proposals/ERC1046/TokenMetadata.test.js
  test/token/ERC20/MintableToken.behavior.js
  test/token/ERC20/PausableToken.test.js
  test/token/ERC20/RBACMintableToken.behavior.js
  test/token/ERC721/ERC721BasicToken.behavior.js
  test/token/ERC721/ERC721Token.test.js
Labels: area:tests, kind:improvement

#1086 Add ERC165Query library
  contracts/introspection/ERC165Checker.sol
  contracts/mocks/ERC165/ERC165InterfacesSupported.sol
  contracts/mocks/ERC165/ERC165NotSupported.sol
  contracts/mocks/ERC165CheckerMock.sol
  test/introspection/ERC165Checker.test.js
Labels: area:contracts, kind:feature

#1228 Role tests
  contracts/access/rbac/Roles.sol
  contracts/mocks/RolesMock.sol
  test/access/rbac/RBAC.test.js
  test/access/rbac/Roles.test.js
Labels: area:contracts, kind:feature

#1229 Removed RBAC tokens
  contracts/mocks/RBACCappedTokenMock.sol
  contracts/token/ERC20/RBACMintableToken.sol
  test/crowdsale/MintedCrowdsale.test.js
  test/token/ERC20/RBACCappedToken.test.js
  test/token/ERC20/RBACMintableToken.behavior.js
  test/token/ERC20/RBACMintableToken.test.js
Labels: area:contracts, breaking change

#1230 Added mint and burn tests for zero amounts.
  test/token/ERC20/BurnableToken.behavior.js
  test/token/ERC20/MintableToken.behavior.js
Labels: area:tests, kind:improvement

#1231 Changed .eq to .equal.
  test/token/ERC20/BurnableToken.behavior.js
  test/token/ERC20/MintableToken.behavior.js
  test/token/ERC20/PausableToken.test.js
  test/token/ERC20/StandardToken.test.js
  test/token/ERC20/TokenVesting.test.js
  test/token/ERC721/ERC721BasicToken.behavior.js
Labels: area:tests, kind:improvement

#1154 ERC721 pausable token
  contracts/mocks/ERC721PausableTokenMock.sol
  contracts/token/ERC721/ERC721PausableToken.sol
  test/token/ERC721/ERC721PausableToken.test.js
  test/token/ERC721/ERC721PausedToken.behavior.js
Labels: area:contracts, kind:feature

#1186 ci: trigger docs update on tag
  .travis.yml
  scripts/ci/trigger_docs_update
Labels: area:automation, kind:feature

#1235 Roles can now be transfered.
  contracts/access/rbac/Roles.sol
  contracts/mocks/RolesMock.sol
  test/access/rbac/Roles.test.js
Labels: area:contracts, kind:feature

#1238 Implementation of TokenEscrow contract (#1099)
  contracts/payment/TokenEscrow.sol
  test/payment/TokenEscrow.test.js
Labels: area:contracts, kind:feature

#1207 Added Events tests of Pausable contract
  test/lifecycle/Pausable.test.js
Labels: area:tests, kind:improvement

#1181 Rename events to past-tense
  CODE_STYLE.md
  contracts/crowdsale/Crowdsale.sol
  contracts/crowdsale/distribution/FinalizableCrowdsale.sol
  contracts/lifecycle/Pausable.sol
  contracts/token/ERC20/BurnableToken.sol
  test/crowdsale/AllowanceCrowdsale.test.js
  test/crowdsale/Crowdsale.test.js
  test/crowdsale/FinalizableCrowdsale.test.js
  test/crowdsale/MintedCrowdsale.behavior.js
  test/lifecycle/Pausable.test.js
  test/token/ERC20/BurnableToken.behavior.js
  test/token/ERC20/PausableToken.test.js
Labels: area:contracts, breaking change, kind:improvement

#1243 fix: refactor sign.js and related tests
  package-lock.json
  package.json
  test/AutoIncrementing.test.js
  test/helpers/sign.js
  test/library/ECRecovery.test.js
Labels: area:tests, kind:improvement

#1171 Added "_" sufix to internal variables
  CODE_STYLE.md
  contracts/crowdsale/distribution/RefundableCrowdsale.sol
  contracts/introspection/SupportsInterfaceWithLookup.sol
  contracts/mocks/ERC721ReceiverMock.sol
  contracts/payment/Escrow.sol
  contracts/token/ERC20/StandardToken.sol
Labels: area:contracts, kind:improvement

#1247 True Ownership
  contracts/mocks/SecondaryMock.sol
  contracts/ownership/Secondary.sol
  contracts/payment/Escrow.sol
  test/ownership/Secondary.test.js
  test/payment/Escrow.behavior.js
  test/payment/Escrow.test.js
Labels: area:contracts, breaking change, kind:feature
