Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2018-04, with the labels that each got.

#865 Fix SafeMath test file
  contracts/mocks/SafeMathMock.sol
  test/helpers/assertJump.js
  test/math/SafeMath.test.js
Labels: review

#867 Add missing await in IndividuallyCappedCrowdsale
  test/crowdsale/IndividuallyCappedCrowdsale.test.js
Labels: review

#866 Remove collaborators and audits from README
  README.md
Labels: review

#885 Various fixes and formatting chores
  .soliumrc.json
  contracts/Bounty.sol
  contracts/DayLimit.sol
  contracts/ECRecovery.sol
  contracts/LimitBalance.sol
  contracts/ReentrancyGuard.sol
  contracts/crowdsale/Crowdsale.sol
  contracts/crowdsale/distribution/utils/RefundVault.sol
  contracts/crowdsale/price/IncreasingPriceCrowdsale.sol
  contracts/crowdsale/validation/TimedCrowdsale.sol
  contracts/examples/SimpleSavingsWallet.sol
  contracts/mocks/ERC223TokenMock.sol
  contracts/mocks/ERC721ReceiverMock.sol
  contracts/mocks/MessageHelper.sol
  contracts/mocks/ReentrancyAttack.sol
  contracts/mocks/ReentrancyMock.sol
  contracts/ownership/HasNoEther.sol
  contracts/ownership/Heritable.sol
  contracts/payment/PullPayment.sol
  contracts/payment/SplitPayment.sol
  contracts/token/ERC20/TokenTimelock.sol
  contracts/token/ERC20/TokenVesting.sol
  contracts/token/ERC721/ERC721BasicToken.sol
  contracts/token/ERC721/ERC721Token.sol
  contracts/token/ERC827/ERC827.sol
  contracts/token/ERC827/ERC827Token.sol
Labels: review

#870 Add StandardBurnableToken implementation
  contracts/mocks/StandardBurnableTokenMock.sol
  contracts/token/ERC20/BurnableToken.sol
  contracts/token/ERC20/StandardBurnableToken.sol
  test/helpers/expectEvent.js
  test/token/ERC20/BurnableToken.behaviour.js
  test/token/ERC20/BurnableToken.test.js
  test/token/ERC20/StandardBurnableToken.test.js
Labels: review

#883 Bouncer contract implementation
  contracts/ECRecovery.sol
  contracts/access/SignatureBouncer.sol
  contracts/mocks/BouncerMock.sol
  contracts/mocks/ECRecoveryMock.sol
  test/access/SignatureBouncer.test.js
  test/helpers/hashMessage.js
  test/helpers/sign.js
  test/library/ECRecovery.test.js
Labels: review

#886 Rename truffle.js to truffle-config.js
  truffle-config.js
Labels: review

#900 Move misplaced MathMock
  contracts/mocks/MathMock.sol
Labels: review

#899 Remove suggestion to rebase
  CONTRIBUTING.md
Labels: review

#902 Add travis job to run test suite with solc nightly
  .travis.yml
  scripts/test.sh
Labels: enhancement, review

#838 Make ERC827 methods payable
  contracts/mocks/MessageHelper.sol
  contracts/token/ERC827/ERC827.sol
  contracts/token/ERC827/ERC827Token.sol
  test/token/ERC827/ERC827Token.js
Labels: in progress

#904 Clean up npm package
  contracts/.npmignore
  contracts/lifecycle/Migrations.sol
  migrations/.gitkeep
  migrations/1_initial_migration.js
  migrations/2_deploy_contracts.js
  package-lock.json
  package.json
Labels: chore
