Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2019-04, with the labels that each got.

#1698 Remove unused files
  contracts/mocks/Acknowledger.sol
  contracts/mocks/EventEmitter.sol
  contracts/mocks/Failer.sol
  package-lock.json
  package.json
Labels: automation, improvement

#1710 Fix from account in remove role behaviors
  test/behaviors/access/roles/PublicRole.behavior.js
Labels: bug, tests

#1718 Fix/rename anyone account #1357
  test/access/Roles.test.js
  test/behaviors/access/roles/PublicRole.behavior.js
  test/crowdsale/FinalizableCrowdsale.test.js
  test/crowdsale/IndividuallyCappedCrowdsale.test.js
  test/crowdsale/PausableCrowdsale.test.js
  test/crowdsale/RefundableCrowdsale.test.js
  test/crowdsale/WhitelistCrowdsale.test.js
  test/cryptography/ECDSA.test.js
  test/drafts/ERC1820Implementer.test.js
  test/drafts/ERC20Snapshot.test.js
  test/drafts/SignatureBouncer.test.js
  test/lifecycle/Pausable.test.js
  test/ownership/Ownable.behavior.js
  test/ownership/Secondary.test.js
  test/token/ERC20/behaviors/ERC20Capped.behavior.js
  test/token/ERC20/behaviors/ERC20Mintable.behavior.js
  test/token/ERC721/ERC721.behavior.js
  test/token/ERC721/ERC721.test.js
  test/token/ERC721/ERC721MintBurn.behavior.js
  test/utils/Address.test.js
Labels: tests

#1684 Feature/erc777 #1159
  CHANGELOG.md
  contracts/drafts/ERC777/ERC777.sol
  contracts/drafts/ERC777/IERC777.sol
  contracts/drafts/ERC777/IERC777Recipient.sol
  contracts/drafts/ERC777/IERC777Sender.sol
  contracts/mocks/ERC777Mock.sol
  contracts/mocks/ERC777SenderRecipientMock.sol
  package-lock.json
  package.json
  test/drafts/ERC777/ERC777.behavior.js
  test/drafts/ERC777/ERC777.test.js
Labels: contracts

#1722 Update stalebot wording and timing.
  .github/stale.yml
Labels: automation

#1720 Release automation
  package-lock.json
  package.json
  scripts/release/release.sh
  scripts/release/update-changelog-release-date.js
  scripts/release/update-ethpm-version.js
Labels: automation, feature

#1708 New documentation setup
  .gitignore
  .travis.yml
  DOCUMENTATION.md
  contracts/access/README.md
  contracts/crowdsale/README.md
  contracts/payment/PaymentSplitter.sol
  contracts/token/ERC20/README.md
  docs/get-started.md
  docs/learn-about-access-control.md
  docs/learn-about-crowdsales.md
  docs/learn-about-tokens.md
  docs/learn-about-utilities.md
  docs/sidebar.json
  netlify.toml
  package-lock.json
  package.json
  scripts/ci/trigger_docs_update
  scripts/docgen.sh
  scripts/docsite.sh
Labels: automation, feature

#1721 Add a vault to PostDeliveryCrowdsale.
  CHANGELOG.md
  contracts/crowdsale/distribution/PostDeliveryCrowdsale.sol
Labels: bug, contracts
