Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2023-03, with the labels that each got.

#4082 Fix an upgrade replay bug in Governor.propose
  contracts/governance/Governor.sol
Labels: bug, ignore-changeset

#4085 docs: minor grammar fix
  contracts/governance/Governor.sol
Labels: ignore-changeset

#4088 Fix empty short string encoding
  contracts/utils/ShortStrings.sol
  test/utils/ShortStrings.test.js
Labels: bug, ignore-changeset

#4084 Formal verification using Certora
  .github/workflows/formal-verification.yml
  certora/.gitignore
  certora/Makefile
  certora/applyHarness.patch
  certora/harnesses/AccessControlHarness.sol
  certora/harnesses/ERC20FlashMintHarness.sol
  certora/harnesses/ERC20PermitHarness.sol
  certora/harnesses/ERC20VotesHarness.sol
  certora/harnesses/ERC3156FlashBorrowerHarness.sol
  certora/harnesses/WizardControlFirstPriority.sol
  certora/harnesses/WizardFirstTry.sol
  certora/munged/.gitignore
  certora/run.js
  certora/scripts/Governor.sh
  certora/scripts/GovernorCountingSimple-counting.sh
  certora/scripts/WizardControlFirstPriority.sh
  certora/scripts/WizardFirstTry.sh
  certora/scripts/sanity.sh
  certora/scripts/verifyAll.sh
  certora/specs.json
  certora/specs/AccessControl.spec
  certora/specs/ERC20.spec
  certora/specs/ERC20FlashMint.spec
  certora/specs/GovernorBase.spec
  certora/specs/GovernorCountingSimple.spec
  certora/specs/RulesInProgress.spec
  certora/specs/helpers.spec
  certora/specs/methods/IERC20.spec
  certora/specs/methods/IERC2612.spec
  certora/specs/methods/IERC3156.spec
  certora/specs/sanity.spec
  package-lock.json
  package.json
  requirements.txt
Labels: ignore-changeset, formal-verification

#4094 Add FV specs for Ownable and Ownable2Steps
  certora/harnesses/Ownable2StepHarness.sol
  certora/harnesses/OwnableHarness.sol
  certora/run.js
  certora/specs.json
  certora/specs/Ownable.spec
  certora/specs/Ownable2Step.spec
  certora/specs/methods/IOwnable.spec
  certora/specs/methods/IOwnable2Step.spec
Labels: ignore-changeset, formal-verification

#4099 Add effect checks on the accesscontrol specs
  certora/specs/AccessControl.spec
Labels: ignore-changeset, formal-verification

#4101 Throw error when requested specs are not found
  certora/run.js
Labels: ignore-changeset

#4100 Add FV specification for ERC20Wrapper
  .changeset/tender-needles-dance.md
  certora/harnesses/ERC20PermitHarness.sol
  certora/harnesses/ERC20WrapperHarness.sol
  certora/run.js
  certora/specs.json
  certora/specs/ERC20Wrapper.spec
  contracts/token/ERC20/extensions/ERC20Wrapper.sol
Labels: ignore-changeset, formal-verification

#4103 Credit YieldBox for virtual offset
  docs/modules/ROOT/pages/erc4626.adoc
Labels: ignore-changeset

#4112 Run formal verification when label is added
  .github/workflows/formal-verification.yml
Labels: ignore-changeset

#4090 Clarify Governor Bravo compatibility scope
  docs/modules/ROOT/pages/governance.adoc
Labels: ignore-changeset

#4114 Update certora/README.md
  certora/README.md
Labels: ignore-changeset

#4117 Add Pausable FV
  .gitignore
  certora/harnesses/PausableHarness.sol
  certora/specs.json
  certora/specs/Pausable.spec
Labels: ignore-changeset, formal-verification

#4129 Fix typo in README
  README.md
Labels: ignore-changeset

#4079 Make AccessControlDefaultAdminRules delay configurable
  contracts/access/AccessControlDefaultAdminRules.sol
  contracts/access/IAccessControlDefaultAdminRules.sol
  test/access/AccessControl.behavior.js
  test/access/AccessControlDefaultAdminRules.test.js
  test/utils/introspection/SupportsInterface.behavior.js
Labels: ignore-changeset

#4145 Update IERC3156FlashBorrower.sol
  contracts/interfaces/IERC3156FlashBorrower.sol
Labels: ignore-changeset
