Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2023-01, with the labels that each got.

#3916 Fix docs for Math.log256
  contracts/utils/math/Math.sol
Labels: ignore-changelog

#3917 Rename param to match the interface
  contracts/token/common/ERC2981.sol
Labels: ignore-changelog

#3933 Improve ERC20.decimals documentation
  contracts/token/ERC20/ERC20.sol
Labels: ignore-changelog

#3941 Add warning in next-v5.0 branch readme
  README.md
Labels: ignore-changelog

#3921 Fix ERC20._update
  contracts/mocks/ERC20Mock.sol
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC20/extensions/ERC20Capped.sol
  contracts/token/ERC20/extensions/ERC20Snapshot.sol
  test/token/ERC20/ERC20.test.js
  test/token/ERC20/extensions/ERC20Burnable.behavior.js
  test/token/ERC20/extensions/ERC20FlashMint.test.js
  test/token/ERC20/extensions/ERC20Wrapper.test.js
Labels: ignore-changelog

#3949 Pin Slither to 0.9.1
  .github/workflows/checks.yml
Labels: ignore-changelog

#3930 Prepare tests for hardhat-exposed transition
  contracts/mocks/ERC721VotesMock.sol
  contracts/mocks/VotesMock.sol
  package-lock.json
  package.json
  test/finance/VestingWallet.test.js
  test/governance/utils/Votes.behavior.js
  test/governance/utils/Votes.test.js
  test/helpers/enums.js
  test/helpers/math.js
  test/token/ERC20/extensions/ERC20Votes.test.js
  test/token/ERC20/extensions/ERC20VotesComp.test.js
  test/token/ERC721/extensions/ERC721Consecutive.test.js
  test/token/ERC721/extensions/ERC721Votes.test.js
Labels: ignore-changelog

#3948 Fix governance tutorial contract
  docs/modules/ROOT/pages/governance.adoc
Labels: ignore-changelog

#3952 Add docs on non-stability of internal function use
  docs/modules/ROOT/pages/extending-contracts.adoc
Labels: ignore-changelog

#3953 Use actionlint on GitHub Actions workflows
  .github/workflows/actionlint.yml
Labels: ignore-changelog

#3955 Ignore reentrancy in`executeBatch` and update Slither config
  .github/workflows/checks.yml
  contracts/governance/TimelockController.sol
  slither.config.json
Labels: ignore-changelog

#3956 Clean up after merging master into next-v5.0
  contracts/mocks/token/ERC20ReturnFalseMock.sol
  slither.config.json
  test/helpers/map-values.js
Labels: ignore-changelog

#3958 Show if event parameter is indexed in docs
  docs/templates/helpers.js
Labels: documentation, ignore-changelog

#3966 Update guidelines and project documentation
  .github/workflows/checks.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  GUIDELINES.md
  LICENSE
  README.md
  SECURITY.md
  audits/2017-03.md
  audits/2018-10.pdf
  audits/2022-10-Checkpoints.pdf
  audits/2022-10-ERC4626.pdf
  audits/README.md
  certora/reports/2021-10.pdf
  certora/reports/2022-03.pdf
  certora/reports/2022-05.pdf
  docs/README.md
Labels: ignore-changelog

#3970 Use allow-reachable delegatecall in Multicall
  contracts/utils/Multicall.sol
Labels: ignore-changelog

#3915 Automate release process via Changesets
  .changeset/beige-buses-drop.md
  .changeset/config.json
  .changeset/curvy-shrimps-enjoy.md
  .changeset/curvy-suns-sort.md
  .changeset/famous-rules-burn.md
  .changeset/funny-rockets-compete.md
  .changeset/gold-chicken-clean.md
  .changeset/healthy-squids-stare.md
  .changeset/lemon-dogs-kiss.md
  .changeset/little-kiwis-ring.md
  .changeset/pretty-hornets-play.md
  .changeset/tame-ladybugs-sit.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/changelog.yml
  .github/workflows/changeset.yml
  .github/workflows/release-cycle.yml
  CHANGELOG.md
  certora/scripts/sanity.sh
  certora/scripts/verifyAll.sh
  package-lock.json
  package.json
  scripts/prepare-docs.sh
  scripts/release/format-changelog.js
  scripts/release/release.sh
  scripts/release/synchronize-versions.js
  scripts/release/update-changelog-release-date.js
  scripts/release/update-comment.js
  scripts/release/version.sh
  scripts/release/workflow/exit-prerelease.sh
  scripts/release/workflow/github-release.js
  scripts/release/workflow/pack.sh
  scripts/release/workflow/prepare-release-merge.sh
  scripts/release/workflow/publish.sh
  scripts/release/workflow/rerun.js
  scripts/release/workflow/set-changesets-pr-title.js
  scripts/release/workflow/start.sh
  scripts/release/workflow/state.js
Labels: ignore-changeset

#3972 Change job titles in `release-cycle.yml`
  .github/workflows/release-cycle.yml
Labels: ignore-changeset

#3988 fix: lint should not override files
  package.json
Labels: ignore-changeset

#4000 Rename `ERC20ReturnFalseMock copy.sol` to `ERC20ReturnFalseMock.sol`
  contracts/mocks/token/ERC20ReturnFalseMock.sol
Labels: ignore-changeset

#4002 Add guidelines for pull requests
  GUIDELINES.md
Labels: ignore-changeset

#3994 Fix Governance docs reference to blocktime
  docs/modules/ROOT/pages/governance.adoc
Labels: ignore-changeset

#4014 Remove outdated note about virtual view functions
  docs/modules/ROOT/pages/extending-contracts.adoc
Labels: ignore-changeset

#4015 Fix typos
  contracts/governance/IGovernor.sol
Labels: ignore-changeset

#3967 Check storage layout consistency in PRs
  .github/actions/storage-layout/action.yml
  .github/workflows/checks.yml
  package-lock.json
  package.json
  scripts/checks/compare-layout.js
  scripts/checks/extract-layout.js
Labels: ignore-changeset
