Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2023-07, with the labels that each got.

#4398 Implement recommendations from 5.0 audit Phase 1A
  contracts/governance/TimelockController.sol
  contracts/governance/utils/IVotes.sol
  contracts/interfaces/draft-IERC6093.sol
  contracts/token/ERC1155/ERC1155.sol
  contracts/token/ERC1155/IERC1155.sol
  contracts/token/ERC1155/extensions/ERC1155Pausable.sol
  contracts/token/ERC1155/extensions/ERC1155Supply.sol
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC20/IERC20.sol
  contracts/token/ERC20/extensions/ERC20Burnable.sol
  contracts/token/ERC20/extensions/ERC20Capped.sol
  contracts/token/ERC20/extensions/ERC20FlashMint.sol
  contracts/token/ERC20/extensions/ERC20Pausable.sol
  contracts/token/ERC20/extensions/ERC20Votes.sol
  contracts/token/ERC20/extensions/ERC20Wrapper.sol
  contracts/token/ERC721/ERC721.sol
  contracts/token/ERC721/extensions/ERC721Pausable.sol
  contracts/utils/Nonces.sol
  contracts/utils/structs/Checkpoints.sol
  scripts/generate/templates/Checkpoints.js
  test/governance/utils/Votes.behavior.js
  test/token/ERC1155/ERC1155.behavior.js
  test/token/ERC1155/ERC1155.test.js
  test/token/ERC1155/extensions/ERC1155Burnable.test.js
  test/token/ERC1155/extensions/ERC1155Pausable.test.js
  test/token/ERC1155/extensions/ERC1155Supply.test.js
  test/token/ERC1155/extensions/ERC1155URIStorage.test.js
  test/token/ERC1155/utils/ERC1155Holder.test.js
  test/token/ERC20/ERC20.behavior.js
  test/token/ERC20/ERC20.test.js
  test/token/ERC20/extensions/ERC20Burnable.behavior.js
  test/token/ERC20/extensions/ERC20Capped.behavior.js
  test/token/ERC20/extensions/ERC20FlashMint.test.js
  test/token/ERC20/extensions/ERC20Pausable.test.js
  test/token/ERC20/extensions/ERC20Votes.test.js
  test/token/ERC20/extensions/ERC20Wrapper.test.js
  test/token/ERC20/extensions/ERC4626.test.js
  test/token/ERC721/extensions/ERC721Votes.test.js
Labels: ignore-changeset

#4414 Implement ERC165 tests realted to invalidID
  test/utils/introspection/SupportsInterface.behavior.js
Labels: ignore-changeset

#4423 Remove retyped and renamed storage layout annotations
  contracts/governance/Governor.sol
  contracts/governance/extensions/GovernorPreventLateQuorum.sol
  contracts/governance/extensions/GovernorTimelockCompound.sol
  contracts/governance/extensions/GovernorVotesQuorumFraction.sol
  contracts/governance/utils/Votes.sol
  contracts/proxy/utils/Initializable.sol
  scripts/upgradeable/upgradeable.patch
Labels: ignore-changeset

#4421 Add back IGovernor to docs
  contracts/governance/README.adoc
Labels: ignore-changeset

#4396 Add `ERC2771Forwarder` fuzz tests for avoiding loss of unused ETH
  contracts/metatx/ERC2771Forwarder.sol
  test/metatx/ERC2771Forwarder.t.sol
Labels: ignore-changeset

#4438 Improve BeaconProxy documentation for storage slot
  contracts/proxy/beacon/BeaconProxy.sol
Labels: ignore-changeset

#4437 Improve custom error helper when there is no match
  test/helpers/customError.js
Labels: ignore-changeset

#4440 Add suggested remappings in readme
  README.md
Labels: ignore-changeset

#4132 Add custom linting rules
  .solhint.json
  package-lock.json
  package.json
  scripts/solhint-custom/index.js
  scripts/solhint-custom/package.json
  solhint.config.js
Labels: ignore-changeset

#4436 Remove unused imports
  contracts/access/AccessControl.sol
  contracts/governance/extensions/GovernorTimelockCompound.sol
  contracts/mocks/token/ERC20PermitNoRevertMock.sol
  contracts/proxy/transparent/ProxyAdmin.sol
  contracts/proxy/utils/Initializable.sol
  contracts/token/ERC20/extensions/ERC20Votes.sol
  contracts/token/ERC721/extensions/ERC721Royalty.sol
  scripts/upgradeable/transpile.sh
  test/token/ERC20/extensions/ERC4626.t.sol
Labels: ignore-changeset

#4443 Remove unnecessary explicit assignment override
  contracts/proxy/utils/UUPSUpgradeable.sol
  contracts/utils/cryptography/EIP712.sol
  scripts/upgradeable/upgradeable.patch
Labels: ignore-changeset

#4452 Fix typos in the tests
  test/governance/extensions/GovernorWithParams.test.js
  test/helpers/governance.js
Labels: ignore-changeset

#4454 Natspec update for TimelockController
  contracts/governance/TimelockController.sol
Labels: ignore-changeset

#4359 Change access folder structure
  .changeset/spicy-sheep-eat.md
  contracts/access/README.adoc
  contracts/access/extensions/AccessControlDefaultAdminRules.sol
  contracts/access/extensions/AccessControlEnumerable.sol
  contracts/access/extensions/IAccessControlDefaultAdminRules.sol
  contracts/access/extensions/IAccessControlEnumerable.sol
  test/access/extensions/AccessControlDefaultAdminRules.test.js
  test/access/extensions/AccessControlEnumerable.test.js
Labels: breaking change, idea

#4150 Refactor DoubleEndedQueue
  .changeset/strong-poems-thank.md
  certora/harnesses/DoubleEndedQueueHarness.sol
  certora/run.js
  certora/specs/DoubleEndedQueue.spec
  certora/specs/helpers/helpers.spec
  contracts/utils/structs/DoubleEndedQueue.sol
  requirements.txt
Labels: formal-verification

#4480 Add custom errors to docs
  contracts/access/AccessControl.sol
  contracts/interfaces/README.adoc
  contracts/interfaces/draft-IERC6093.sol
  docs/templates/contract.hbs
  docs/templates/properties.js
Labels: ignore-changeset

#4458 Avoid `returndatacopy` in ERC2771Forwarder by calling via assembly
  contracts/metatx/ERC2771Context.sol
  contracts/metatx/ERC2771Forwarder.sol
  test/metatx/ERC2771Forwarder.test.js
Labels: ignore-changeset

#4476 Improve ERC4626 fees example
  contracts/mocks/docs/ERC4626Fees.sol
  contracts/mocks/token/ERC4646FeesMock.sol
  test/token/ERC20/extensions/ERC4626.test.js
Labels: ignore-changeset

#4487 Fix issues in the ERC4646Fee documentation
  contracts/mocks/docs/ERC4626Fees.sol
Labels: documentation, ignore-changeset, area: erc4626
