Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2023-11, with the labels that each got.

#4721 Update docs for Ownable2Step
  contracts/access/Ownable2Step.sol
  docs/modules/ROOT/pages/access-control.adoc
Labels: ignore-changeset

#4722 Improve ERC4626 virtual offset notes
  contracts/token/ERC20/extensions/ERC4626.sol
Labels: ignore-changeset

#4723 Migrate finance tests to ethers.js
  test/finance/VestingWallet.behavior.js
  test/finance/VestingWallet.test.js
Labels: ignore-changeset

#4691 Add `AccessManager` guide
  contracts/mocks/docs/access-control/AccessControlERC20MintBase.sol
  contracts/mocks/docs/access-control/AccessControlERC20MintMissing.sol
  contracts/mocks/docs/access-control/AccessControlERC20MintOnlyRole.sol
  contracts/mocks/docs/access-control/AccessManagedERC20MintBase.sol
  contracts/mocks/docs/access-control/MyContractOwnable.sol
  docs/modules/ROOT/images/access-control-multiple.svg
  docs/modules/ROOT/images/access-manager-functions.svg
  docs/modules/ROOT/images/access-manager.svg
  docs/modules/ROOT/pages/access-control.adoc
Labels: ignore-changeset

#4710 Migrate `AccessManager` tests to ethers
  contracts/mocks/AuthorityMock.sol
  test/access/Ownable.test.js
  test/access/manager/AccessManaged.test.js
  test/access/manager/AccessManager.behavior.js
  test/access/manager/AccessManager.predicate.js
  test/access/manager/AccessManager.test.js
  test/access/manager/AuthorityUtils.test.js
  test/helpers/access-manager.js
  test/helpers/constants.js
  test/helpers/namespaced-storage.js
Labels: ignore-changeset

#4731 Rename VotesTimestamp to ERC20VotesTimestampMock
  contracts/mocks/token/ERC20VotesTimestampMock.sol
Labels: ignore-changeset

#4683 Update SECURITY.md and remove support for 2.x version
  SECURITY.md
Labels: ignore-changeset

#4737 Migrate Context & ERC2771 tests to ethers.js
  test/helpers/account.js
  test/helpers/math.js
  test/metatx/ERC2771Context.test.js
  test/metatx/ERC2771Forwarder.test.js
  test/utils/Context.behavior.js
  test/utils/Context.test.js
Labels: tests, ignore-changeset

#4749 Migrate utils-cryptography to ethers
  test/helpers/eip712.js
  test/helpers/sign.js
  test/utils/cryptography/ECDSA.test.js
  test/utils/cryptography/EIP712.test.js
  test/utils/cryptography/MessageHashUtils.test.js
  test/utils/cryptography/SignatureChecker.test.js
Labels: ignore-changeset

#4750 Migrate EIP712 to ethersjs
  scripts/upgradeable/upgradeable.patch
  test/governance/Governor.test.js
  test/governance/extensions/GovernorWithParams.test.js
  test/governance/utils/Votes.behavior.js
  test/helpers/eip712-types.js
  test/helpers/eip712.js
  test/token/ERC20/extensions/ERC20Permit.test.js
  test/token/ERC20/extensions/ERC20Votes.test.js
  test/utils/cryptography/EIP712.test.js
Labels: ignore-changeset

#4739 Migrate address to ethersjs
  test/utils/Address.test.js
Labels: ignore-changeset

#4748 Migrate utils-structs tests to ethersjs
  package-lock.json
  package.json
  test/helpers/random.js
  test/utils/structs/BitMap.test.js
  test/utils/structs/Checkpoints.test.js
  test/utils/structs/DoubleEndedQueue.test.js
  test/utils/structs/EnumerableMap.behavior.js
  test/utils/structs/EnumerableMap.test.js
  test/utils/structs/EnumerableSet.behavior.js
  test/utils/structs/EnumerableSet.test.js
Labels: ignore-changeset

#4553 Optimized gas costs in `ceilDiv`
  .changeset/angry-dodos-grow.md
  contracts/utils/math/Math.sol
  test/utils/math/Math.t.sol
Labels: gas optimization

#4733 Implement revert tests for VestingWallet
  test/finance/VestingWallet.behavior.js
  test/finance/VestingWallet.test.js
Labels: ignore-changeset

#4736 Migrate utils to ethersjs v6
  contracts/mocks/MulticallHelper.sol
  contracts/mocks/StorageSlotMock.sol
  test/helpers/random.js
  test/utils/Arrays.test.js
  test/utils/Base64.test.js
  test/utils/Create2.test.js
  test/utils/Multicall.test.js
  test/utils/Nonces.test.js
  test/utils/Pausable.test.js
  test/utils/ReentrancyGuard.test.js
  test/utils/ShortStrings.test.js
  test/utils/StorageSlot.test.js
  test/utils/Strings.test.js
Labels: tests, ignore-changeset

#4751 Create FUNDING.json
  FUNDING.json
Labels: ignore-changeset

#4755 Add note in ERC20Wrapper about rebasing tokens
  contracts/token/ERC20/extensions/ERC20Wrapper.sol
Labels: ignore-changeset

#4760 Refactor enumerableMap generate and tests
  scripts/generate/templates/EnumerableMap.js
  scripts/generate/templates/EnumerableMap.opts.js
  test/utils/structs/EnumerableMap.behavior.js
  test/utils/structs/EnumerableMap.test.js
Labels: tests, ignore-changeset

#4762 Refactor EnumerableSet generation and tests
  scripts/generate/templates/EnumerableSet.js
  scripts/generate/templates/EnumerableSet.opts.js
  test/utils/structs/EnumerableSet.behavior.js
  test/utils/structs/EnumerableSet.test.js
Labels: tests, ignore-changeset

#4743 Migrate erc20 to ethersjs
  test/token/ERC20/ERC20.behavior.js
  test/token/ERC20/ERC20.test.js
  test/token/ERC20/extensions/ERC20Wrapper.test.js
Labels: tests, ignore-changeset

#4746 Migrate proxy tests folder to ethersjs
  test/helpers/erc1967.js
  test/proxy/Clones.behaviour.js
  test/proxy/Clones.test.js
  test/proxy/ERC1967/ERC1967Proxy.test.js
  test/proxy/ERC1967/ERC1967Utils.test.js
  test/proxy/Proxy.behaviour.js
  test/proxy/beacon/BeaconProxy.test.js
  test/proxy/beacon/UpgradeableBeacon.test.js
  test/proxy/transparent/ProxyAdmin.test.js
  test/proxy/transparent/TransparentUpgradeableProxy.behaviour.js
  test/proxy/transparent/TransparentUpgradeableProxy.test.js
  test/proxy/utils/Initializable.test.js
  test/proxy/utils/UUPSUpgradeable.test.js
Labels: ignore-changeset

#4766 Add Governor note for state changes between proposal creation and execution
  contracts/governance/IGovernor.sol
Labels: ignore-changeset
