Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2023-06, with the labels that each got.

#4290 Move some changeset to the "Removals" section of CHANGELOG
  .changeset/beige-ducks-flow.md
  .changeset/dirty-mangos-sort.md
  .changeset/fluffy-gifts-build.md
  .changeset/friendly-suits-camp.md
  .changeset/hungry-impalas-perform.md
  .changeset/selfish-queens-rest.md
  .changeset/spicy-ducks-cough.md
  .changeset/swift-berries-sort.md
  .changeset/tame-geckos-search.md
  .changeset/three-weeks-double.md
  .changeset/unlucky-snakes-drive.md
  CHANGELOG.md
Labels: ignore-changeset

#4306 Make CHANGELOG more compact for improved readability
  CHANGELOG.md
Labels: ignore-changeset

#4340 `IERC1155`: Fix `safeBatchTransferFrom` documentation
  contracts/token/ERC1155/IERC1155.sol
Labels: ignore-changeset

#4335 Update README.md
  README.md
Labels: ignore-changeset

#4336 Update index.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: ignore-changeset

#4302 Cleanup the structure of GovernorTimelockControl.test.js
  test/governance/extensions/GovernorTimelockControl.test.js
Labels: ignore-changeset

#4010 Add `GUIDELINES.md` for marking `abstract` contracts
  GUIDELINES.md
  contracts/token/ERC1155/ERC1155.sol
  contracts/token/ERC1155/utils/ERC1155Holder.sol
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC721/ERC721.sol
  contracts/token/ERC721/utils/ERC721Holder.sol
  test/token/ERC1155/utils/ERC1155Holder.test.js
  test/token/ERC721/utils/ERC721Holder.test.js
Labels: ignore-changeset

#4352 Merge release-v4.9 branch
  CHANGELOG.md
  contracts/governance/Governor.sol
  contracts/package.json
  package.json
Labels: ignore-changeset

#4348 Change behavior of ceilDiv(0, 0) and improve test coverage
  .changeset/blue-scissors-design.md
  contracts/mocks/token/ERC20Reentrant.sol
  contracts/mocks/token/ERC4626LimitsMock.sol
  contracts/utils/math/Math.sol
  test/token/ERC1155/ERC1155.behavior.js
  test/token/ERC20/extensions/ERC4626.test.js
  test/token/ERC721/extensions/ERC721Burnable.test.js
  test/token/ERC721/extensions/ERC721Consecutive.test.js
  test/utils/math/Math.test.js
  test/utils/structs/Checkpoints.test.js
Labels: ignore-changeset

#4284 Use ERC721Holder & ERC1155Holder in the TimelockController
  contracts/governance/TimelockController.sol
  scripts/checks/inheritance-ordering.js
Labels: ignore-changeset

#4357 Output contract name where storage inconsistency was found
  scripts/checks/compare-layout.js
Labels: tooling, ignore-changeset

#4362 Remove automatic conflict resolution for merge from release branch
  .github/workflows/release-cycle.yml
  scripts/release/workflow/prepare-release-merge.sh
Labels: ignore-changeset

#4365 Change release cycle `prBackExists` definition
  scripts/release/workflow/state.js
Labels: ignore-changeset

#3781 Improve tests for ERC1155 and ERC721 error handling
  contracts/mocks/token/ERC1155ReceiverMock.sol
  contracts/mocks/token/ERC721ReceiverMock.sol
  test/token/ERC1155/ERC1155.behavior.js
  test/token/ERC721/ERC721.behavior.js
Labels: ignore-changeset

#4371 Use clones for testing non ERC1967 proxies
  test/proxy/utils/UUPSUpgradeable.test.js
Labels: tests, ignore-changeset

#4374 Fix attempt to delete nonexistent npm tag
  scripts/release/workflow/publish.sh
Labels: ignore-changeset

#4373 Merge branch 'release-v4.9' into master
  .changeset/shy-crews-teach.md
  CHANGELOG.md
  contracts/package.json
  contracts/utils/cryptography/MerkleProof.sol
  package-lock.json
  package.json
Labels: ignore-changeset

#4376 Improve customError testing
  test/helpers/customError.js
Labels: tests, ignore-changeset

#4369 Update comment to reflect code logic in Ownable.sol
  contracts/access/Ownable.sol
Labels: ignore-changeset

#4381 Rename `ERC1155InsufficientApprovalForAll` to `ERC1155MissingApprovalForAll`
  contracts/interfaces/draft-IERC6093.sol
  contracts/token/ERC1155/ERC1155.sol
  contracts/token/ERC1155/extensions/ERC1155Burnable.sol
  test/token/ERC1155/ERC1155.behavior.js
  test/token/ERC1155/extensions/ERC1155Burnable.test.js
Labels: ignore-changeset

#4389 Add Foundry installation instructions with required warnings
  README.md
  scripts/upgradeable/upgradeable.patch
Labels: ignore-changeset

#4391 Fix details AccessControl-test
  test/access/AccessControl.behavior.js
  test/access/AccessControlEnumerable.test.js
Labels: ignore-changeset

#4386 Fix visibility in ERC721._checkOnERC721Received documentation
  contracts/token/ERC721/ERC721.sol
Labels: ignore-changeset

#4400 Imrove `BitMaps` documentation
  contracts/utils/structs/BitMaps.sol
Labels: ignore-changeset

#4406 Add security considerations to ERC2771Forwarder
  contracts/metatx/ERC2771Forwarder.sol
Labels: ignore-changeset
