Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-12, with the labels that each got.

#5333 Fix typo in paymasterData function comment
  contracts/account/utils/draft-ERC4337Utils.sol
Labels: ignore-changeset

#5336 Remove token value mention in ERC-1155 documentation
  docs/modules/ROOT/pages/erc1155.adoc
Labels: ignore-changeset

#5330 Release v5.2 audit fixes
  .changeset/proud-planes-arrive.md
  GUIDELINES.md
  contracts/account/utils/draft-ERC4337Utils.sol
  contracts/account/utils/draft-ERC7579Utils.sol
  contracts/finance/VestingWallet.sol
  contracts/governance/extensions/GovernorCountingOverridable.sol
  contracts/governance/utils/Votes.sol
  contracts/governance/utils/VotesExtended.sol
  contracts/interfaces/draft-IERC4337.sol
  contracts/interfaces/draft-IERC7579.sol
  contracts/mocks/docs/access-control/AccessControlNonRevokableAdmin.sol
  contracts/proxy/Clones.sol
  contracts/token/ERC20/extensions/ERC1363.sol
  contracts/token/ERC20/utils/SafeERC20.sol
  contracts/utils/Bytes.sol
  contracts/utils/CAIP10.sol
  contracts/utils/CAIP2.sol
  contracts/utils/NoncesKeyed.sol
  contracts/utils/Strings.sol
  test/account/utils/draft-ERC4337Utils.test.js
  test/account/utils/draft-ERC7579Utils.test.js
  test/governance/utils/VotesExtended.test.js
  test/helpers/erc4337.js
  test/utils/Nonces.behavior.js
  test/utils/Strings.t.sol
  test/utils/Strings.test.js
Labels: ignore-changeset

#5339 Fix v5.2 testing
  test/governance/extensions/GovernorCountingOverridable.test.js
Labels: tests, ignore-changeset, CI

#5342 Cherry-pick "Fix v5.2 testing" from the release-v5.2 branch
  test/governance/extensions/GovernorCountingOverridable.test.js
Labels: ignore-changeset

#5329 Fix typo in ERC721 API reference docs
  contracts/token/ERC721/README.adoc
Labels: ignore-changeset

#5340 Run linter on commit instead of push
  .githooks/pre-push
  .husky/pre-commit
  package-lock.json
  package.json
  scripts/prepare.sh
Labels: ignore-changeset

#5350 Allow pass in custom arguments to `shouldSupportInterfaces` test helper
  test/helpers/iterate.js
  test/utils/introspection/SupportsInterface.behavior.js
Labels: ignore-changeset

#5358 Refactor shouldSupportInterfaces helper
  test/utils/introspection/SupportsInterface.behavior.js
Labels: ignore-changeset

#5359 Amend shouldSupportInterfaces refactor
  test/utils/introspection/SupportsInterface.behavior.js
Labels: ignore-changeset

#5356 Fix grammar in documentation
  contracts/governance/extensions/GovernorTimelockCompound.sol
  test/TESTING.md
Labels: ignore-changeset

#5341 Add v5.2 audit report
  audits/2024-12-v5.2.pdf
  audits/README.md
Labels: ignore-changeset

#5361 Fix README.adoc
  contracts/utils/README.adoc
Labels: documentation, ignore-changeset

#5354 fix typo Update inheritance-ordering.js
  scripts/checks/inheritance-ordering.js
Labels: ignore-changeset

#5362 Vendor entrypoint bytecode
  foundry.toml
  test/account/utils/draft-ERC4337Utils.test.js
  test/bin/EntryPoint070.abi
  test/bin/EntryPoint070.bytecode
  test/bin/SenderCreator070.abi
  test/bin/SenderCreator070.bytecode
  test/helpers/erc4337-entrypoint.js
Labels: ignore-changeset

#5353 Add checks to ERC7579Utils.decodeBatch
  contracts/account/utils/draft-ERC7579Utils.sol
  test/account/utils/draft-ERC7579Utils.t.sol
  test/account/utils/draft-ERC7579Utils.test.js
Labels: bug, ignore-changeset

#5368 Remove relative path in solhint.config.js in favor of npm virtual package
  package-lock.json
  scripts/solhint-custom/package.json
  solhint.config.js
Labels: ignore-changeset, CI

#5367 Cherrypick #5353 into release-v5.2
  .changeset/seven-insects-taste.md
  contracts/account/utils/draft-ERC7579Utils.sol
  foundry.toml
  test/account/utils/draft-ERC4337Utils.test.js
  test/account/utils/draft-ERC7579Utils.t.sol
  test/account/utils/draft-ERC7579Utils.test.js
  test/bin/EntryPoint070.abi
  test/bin/EntryPoint070.bytecode
  test/bin/SenderCreator070.abi
  test/bin/SenderCreator070.bytecode
  test/helpers/erc4337-entrypoint.js
Labels: ignore-changeset

#5390 Remove compile_force_framework: hardhat from slither config
  .github/workflows/checks.yml
  slither.config.json
Labels: ignore-changeset, CI

#5322 Use the `asset` getter in `totalAssets`, `_deposit` and `_withdraw` in ERC4626
  .changeset/thin-eels-cross.md
  contracts/token/ERC20/extensions/ERC4626.sol
Labels: ignore-changeset

#5290 Add GovernorSequentialProposalId extension for sequential numbers on proposals
  .changeset/brave-islands-sparkle.md
  .changeset/ten-fishes-fold.md
  contracts/governance/Governor.sol
  contracts/governance/IGovernor.sol
  contracts/governance/extensions/GovernorSequentialProposalId.sol
  contracts/mocks/governance/GovernorSequentialProposalIdMock.sol
  test/governance/Governor.test.js
  test/governance/extensions/GovernorSequentialProposalId.test.js
  test/helpers/governance.js
  test/utils/introspection/SupportsInterface.behavior.js
Labels: area: governance

#5392 Fix envvar setting for test and coverage
  package.json
  scripts/checks/coverage.sh
Labels: ignore-changeset

#5391 Automatically deploy entrypoint, and make it available in the hre
  hardhat/common-contracts.js
  test/account/utils/draft-ERC4337Utils.test.js
  test/helpers/erc4337-entrypoint.js
Labels: tests, ignore-changeset

#5323 Remove unnecessary trailing `/` in prepare-docs.sh
  scripts/prepare-docs.sh
Labels: documentation, ignore-changeset, CI

#5380 Update outdated links in docs
  docs/modules/ROOT/pages/access-control.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: ignore-changeset

#5397 Fix inaccurate comment for callGasLimit function in ERC4337Utils
  contracts/account/utils/draft-ERC4337Utils.sol
Labels: ignore-changeset

#5407 Update links to the eth_sign JSON-RPC method in MessageHashUtils
  contracts/utils/cryptography/MessageHashUtils.sol
Labels: ignore-changeset

#5408 Await `.eventually` test matchers
  test/account/utils/draft-ERC4337Utils.test.js
  test/account/utils/draft-ERC7579Utils.test.js
  test/governance/extensions/GovernorSequentialProposalId.test.js
  test/utils/Nonces.behavior.js
Labels: ignore-changeset
