Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-10, with the labels that each got.

#5234 Add warning about low public key exponent
  contracts/utils/cryptography/RSA.sol
Labels: documentation, ignore-changeset

#5131 Reorganize changelog entries for 5.1
  CHANGELOG.md
Labels: ignore-changeset, release-cycle

#5237 Add 5.1 audit report
  audits/2024-10-v5.1.pdf
  audits/README.md
Labels: ignore-changeset

#5240 Fix typo in CHANGELOG.md
  CHANGELOG.md
Labels: ignore-changeset

#5239 Split StorageSlot into TransientSlot
  contracts/mocks/StorageSlotMock.sol
  contracts/mocks/TransientSlotMock.sol
  contracts/token/ERC20/extensions/draft-ERC20TemporaryApproval.sol
  contracts/utils/README.adoc
  contracts/utils/ReentrancyGuardTransient.sol
  contracts/utils/StorageSlot.sol
  contracts/utils/TransientSlot.sol
  docs/modules/ROOT/pages/utilities.adoc
  scripts/generate/run.js
  scripts/generate/templates/StorageSlot.js
  scripts/generate/templates/StorageSlotMock.js
  scripts/generate/templates/TransientSlot.js
  scripts/generate/templates/TransientSlotMock.js
  test/utils/StorageSlot.test.js
  test/utils/TransientSlot.test.js
Labels: ignore-changeset

#5235 Fix spelling issues in documentation
  docs/modules/ROOT/pages/erc1155.adoc
  docs/modules/ROOT/pages/erc4626.adoc
  docs/modules/ROOT/pages/governance.adoc
Labels: documentation, ignore-changeset

#5269 GovernorCountingOverridable testing with timestamp
  contracts/mocks/VotesExtendedMock.sol
  test/governance/extensions/GovernorCountingOverridable.test.js
Labels: ignore-changeset

#5270 Remove missed changeset from 5.1-rc.1
  .changeset/yellow-tables-sell.md
Labels: ignore-changeset

#5233 Simplify content in security documentation
  docs/modules/ROOT/pages/extending-contracts.adoc
Labels: ignore-changeset

#5271 ERC20: optimized gas costs in `_spendAllowance`
  contracts/token/ERC20/ERC20.sol
Labels: ignore-changeset

#5258 Fuzz tampered tests for `ERC2771Forwarder`
  test/metatx/ERC2771Forwarder.t.sol
  test/metatx/ERC2771Forwarder.test.js
Labels: ignore-changeset

#5273 Bump pragma to 0.8.22 for all contract that depend on ERC1967Utils
  .changeset/seven-donkeys-tap.md
  .github/workflows/checks.yml
  contracts/mocks/DummyImplementation.sol
  contracts/mocks/MerkleTreeMock.sol
  contracts/mocks/Stateless.sol
  contracts/mocks/governance/GovernorStorageMock.sol
  contracts/mocks/proxy/UUPSUpgradeableMock.sol
  contracts/proxy/ERC1967/ERC1967Proxy.sol
  contracts/proxy/ERC1967/ERC1967Utils.sol
  contracts/proxy/beacon/BeaconProxy.sol
  contracts/proxy/transparent/ProxyAdmin.sol
  contracts/proxy/transparent/TransparentUpgradeableProxy.sol
  contracts/proxy/utils/UUPSUpgradeable.sol
  package.json
  scripts/checks/inheritance-ordering.js
  scripts/checks/pragma-consistency.js
Labels: bug, CI

#5276 Bump pragma of files that depend on mcopy
  contracts/mocks/Stateless.sol
  contracts/utils/Bytes.sol
  contracts/utils/CAIP10.sol
  contracts/utils/CAIP2.sol
Labels: ignore-changeset

#5278 Remove unused import in `SafeERC20`
  contracts/token/ERC20/utils/SafeERC20.sol
Labels: ignore-changeset

#5236 Optimize `log2` with a lookup table
  contracts/utils/math/Math.sol
Labels: ignore-changeset
