Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-03, with the labels that each got.

#4938 Fix typo in ERC721Utils.sol
  contracts/token/ERC721/utils/ERC721Utils.sol
Labels: documentation, ignore-changeset

#4937 Improve MerkleProof tests
  test/utils/cryptography/MerkleProof.test.js
Labels: tests, ignore-changeset

#4924 Update documentation in IAccessControl
  contracts/access/IAccessControl.sol
Labels: ignore-changeset

#4940 Remove redundant getVotes call in Governor
  contracts/governance/Governor.sol
Labels: ignore-changeset, gas optimization

#4927 Optimize Clone.sol yul
  contracts/proxy/Clones.sol
Labels: ignore-changeset

#3617 Add a MerkleTree builder
  .changeset/odd-files-protect.md
  .changeset/warm-sheep-cover.md
  contracts/mocks/ArraysMock.sol
  contracts/mocks/MerkleTreeMock.sol
  contracts/utils/Arrays.sol
  contracts/utils/README.adoc
  contracts/utils/cryptography/Hashes.sol
  contracts/utils/cryptography/MerkleProof.sol
  contracts/utils/structs/MerkleTree.sol
  package-lock.json
  package.json
  test/utils/Arrays.test.js
  test/utils/structs/MerkleTree.test.js
Labels: Datastructures, Cryptography

#4944 Remove repetitive words in the docs
  CHANGELOG.md
  contracts/utils/math/Math.sol
Labels: ignore-changeset

#4949 Remove root from MerkleTree
  contracts/mocks/MerkleTreeMock.sol
  contracts/utils/structs/MerkleTree.sol
Labels: ignore-changeset

#4920 Fix typos in utilities and access control docs
  docs/modules/ROOT/pages/access-control.adoc
  docs/modules/ROOT/pages/utilities.adoc
Labels: ignore-changeset

#4964 Remove outdated comment in ERC-20
  contracts/token/ERC20/ERC20.sol
Labels: documentation, ignore-changeset

#4956 Update Solidity files in docs
  contracts/mocks/docs/MyNFT.sol
  contracts/mocks/docs/access-control/AccessControlModified.sol
  contracts/mocks/docs/access-control/AccessControlUnrevokableAdmin.sol
  contracts/mocks/docs/token/ERC1155/GameItems.sol
  contracts/mocks/docs/token/ERC1155/MyERC115HolderContract.sol
  contracts/mocks/docs/token/ERC20/GLDToken.sol
  contracts/mocks/docs/token/ERC721/GameItem.sol
  contracts/mocks/docs/utilities/Base64NFT.sol
  contracts/mocks/docs/utilities/Multicall.sol
  docs/modules/ROOT/pages/erc1155.adoc
  docs/modules/ROOT/pages/erc20.adoc
  docs/modules/ROOT/pages/erc721.adoc
  docs/modules/ROOT/pages/extending-contracts.adoc
  docs/modules/ROOT/pages/governance.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/utilities.adoc
Labels: ignore-changeset

#4968 Remove outdated comment in ERC-20
  contracts/token/ERC20/ERC20.sol
Labels: documentation, ignore-changeset

#4962 Run linter before pushing to git
  .githooks/pre-push
  package.json
Labels: automation, ignore-changeset, CI

#4970 Remove repetitive word from CHANGELOG.md
  CHANGELOG.md
Labels: ignore-changeset

#4545 Optimize nested mapping access in ERC721Enumerable
  contracts/token/ERC721/extensions/ERC721Enumerable.sol
Labels: ignore-changeset, gas optimization

#4538 Remove redundant memory usage in ERC2981 royaltyInfo
  contracts/token/common/ERC2981.sol
Labels: ignore-changeset, gas optimization

#4972 Update ERC2771Forwarder assembly comment
  contracts/metatx/ERC2771Forwarder.sol
Labels: ignore-changeset

#4859 Procedurally generate Arrays.sol
  contracts/utils/Arrays.sol
  scripts/generate/run.js
  scripts/generate/templates/Arrays.js
  scripts/generate/templates/Arrays.opts.js
  test/utils/Arrays.test.js
Labels: ignore-changeset
