Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-09, with the labels that each got.

#5181 Optimizations to P256 operations
  contracts/utils/cryptography/P256.sol
Labels: ignore-changeset

#5173 Add note about 100% royalty in IERC2981
  contracts/interfaces/IERC2981.sol
Labels: ignore-changeset

#5178 Guidelines for named return values
  GUIDELINES.md
Labels: ignore-changeset

#5176 Make padding skip clear in Base64URL encoding
  contracts/utils/Base64.sol
Labels: ignore-changeset

#5175 Clarify Governor events' lack of indexed parameters
  contracts/governance/IGovernor.sol
Labels: ignore-changeset

#5191 Bump version of `ERC20TemporaryApproval` to transient minimum
  contracts/token/ERC20/extensions/draft-ERC20TemporaryApproval.sol
Labels: ignore-changeset

#5193 Tag memory safe assembly blocks
  contracts/governance/Governor.sol
  contracts/metatx/ERC2771Forwarder.sol
  contracts/utils/introspection/ERC165Checker.sol
Labels: ignore-changeset

#5194 Fix typographical errors
  contracts/interfaces/IERC1363Receiver.sol
  contracts/token/ERC1155/utils/ERC1155Utils.sol
  contracts/utils/cryptography/MerkleProof.sol
  contracts/utils/cryptography/RSA.sol
  contracts/utils/structs/CircularBuffer.sol
  contracts/utils/structs/Heap.sol
  scripts/generate/templates/Heap.js
  scripts/generate/templates/MerkleProof.js
  test/utils/structs/MerkleTree.test.js
Labels: ignore-changeset

#5198 Update to match Solidity pragma
  contracts/utils/cryptography/Hashes.sol
  contracts/utils/structs/MerkleTree.sol
Labels: ignore-changeset

#5200 Remove redundant modulo operation in P256
  contracts/utils/cryptography/P256.sol
Labels: ignore-changeset

#5195 Clean dirty addresses and booleans
  contracts/utils/SlotDerivation.sol
  scripts/generate/helpers/sanitize.js
  scripts/generate/templates/Packing.js
  scripts/generate/templates/Slot.opts.js
  scripts/generate/templates/SlotDerivation.js
  scripts/generate/templates/SlotDerivation.t.js
  test/utils/SlotDerivation.t.sol
Labels: ignore-changeset

#5164 refactor: enhance ERC6372 behavior test with detailed checks
  test/governance/utils/ERC6372.behavior.js
Labels: ignore-changeset

#5190 Refactor Heap.sol to remove `index` and `lookup`
  contracts/utils/structs/Heap.sol
  scripts/generate/run.js
  scripts/generate/templates/Heap.js
  scripts/generate/templates/Heap.opts.js
  scripts/generate/templates/Heap.t.js
  test/utils/structs/Heap.t.sol
  test/utils/structs/Heap.test.js
Labels: ignore-changeset

#5205 Clarify reference commits and licenses
  contracts/utils/cryptography/P256.sol
  contracts/utils/cryptography/RSA.sol
Labels: ignore-changeset

#5204 Clarify mapping named parameters
  contracts/governance/extensions/GovernorCountingFractional.sol
Labels: ignore-changeset

#5179 Update documentation of helper interface
  contracts/proxy/transparent/TransparentUpgradeableProxy.sol
Labels: ignore-changeset

#5213 Add note about memory manipulation in MerkleTree
  contracts/utils/structs/MerkleTree.sol
Labels: ignore-changeset

#5214 Disallow empty CircularBuffer setup
  contracts/utils/structs/CircularBuffer.sol
  test/utils/structs/CircularBuffer.test.js
Labels: ignore-changeset

#5222 Fix typo in ERC4626 docs
  docs/modules/ROOT/pages/erc4626.adoc
Labels: documentation, ignore-changeset

#5206 Update and clarify documentation comments
  contracts/finance/VestingWalletCliff.sol
  contracts/governance/extensions/GovernorCountingFractional.sol
  contracts/interfaces/IERC1363Spender.sol
  contracts/utils/cryptography/P256.sol
  contracts/utils/cryptography/RSA.sol
  contracts/utils/structs/CircularBuffer.sol
  docs/modules/ROOT/pages/utilities.adoc
  test/utils/cryptography/RSA.test.js
Labels: ignore-changeset

#5226 Add comment and tests for zero address behavior in Ownable2Step.transferOwnership()
  contracts/access/Ownable2Step.sol
  test/access/Ownable2Step.test.js
Labels: tests, documentation, ignore-changeset

#5227 Add P256 and RSA documentation sections
  contracts/utils/README.adoc
  contracts/utils/cryptography/P256.sol
Labels: documentation, ignore-changeset

#5215 Implement 5.1 Full Audit Naming Suggestions
  contracts/utils/structs/Heap.sol
  contracts/utils/structs/MerkleTree.sol
Labels: ignore-changeset

#5177 Consistently name multiple returned values
  contracts/governance/Governor.sol
  contracts/governance/extensions/GovernorStorage.sol
  contracts/governance/utils/Votes.sol
  contracts/metatx/ERC2771Forwarder.sol
  contracts/token/ERC20/extensions/ERC4626.sol
  contracts/token/common/ERC2981.sol
  contracts/utils/cryptography/ECDSA.sol
  contracts/utils/cryptography/P256.sol
  contracts/utils/structs/Checkpoints.sol
  contracts/utils/structs/EnumerableMap.sol
  contracts/utils/types/Time.sol
  scripts/generate/templates/Checkpoints.js
  scripts/generate/templates/EnumerableMap.js
Labels: ignore-changeset

#5229 Improve VestingWallet's constructor and RSA.pkcs1Sha256 documentation
  contracts/finance/VestingWallet.sol
  contracts/finance/VestingWalletCliff.sol
  contracts/utils/cryptography/RSA.sol
Labels: documentation, ignore-changeset

#5228 Add introduction tag for v5.1 contracts
  contracts/finance/VestingWalletCliff.sol
  contracts/governance/extensions/GovernorCountingFractional.sol
  contracts/token/ERC1155/utils/ERC1155Utils.sol
  contracts/token/ERC20/extensions/ERC1363.sol
  contracts/token/ERC20/extensions/draft-ERC20TemporaryApproval.sol
  contracts/token/ERC721/utils/ERC721Utils.sol
  contracts/utils/Comparators.sol
  contracts/utils/Errors.sol
  contracts/utils/Packing.sol
  contracts/utils/Panic.sol
  contracts/utils/ReentrancyGuardTransient.sol
  contracts/utils/SlotDerivation.sol
  contracts/utils/cryptography/Hashes.sol
  contracts/utils/cryptography/P256.sol
  contracts/utils/cryptography/RSA.sol
  contracts/utils/structs/CircularBuffer.sol
  contracts/utils/structs/Heap.sol
  scripts/generate/templates/Packing.js
  scripts/generate/templates/SlotDerivation.js
Labels: ignore-changeset

#5232 Fix invalid link and typos
  docs/modules/ROOT/pages/utilities.adoc
Labels: ignore-changeset

#5218 Fix P256 corner cases
  .solcover.js
  contracts/utils/cryptography/P256.sol
  test/helpers/iterate.js
  test/utils/cryptography/P256.t.sol
Labels: ignore-changeset
