Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-01, with the labels that each got.

#4815 Fix documentation inaccuracies in Governor
  contracts/governance/extensions/GovernorTimelockAccess.sol
  contracts/governance/extensions/GovernorTimelockCompound.sol
  contracts/governance/extensions/GovernorTimelockControl.sol
Labels: documentation, ignore-changeset

#4546 Add getRoleMembers method to return all accounts that have role
  .changeset/violet-moons-tell.md
  contracts/access/extensions/AccessControlEnumerable.sol
  test/access/AccessControl.behavior.js
Labels: feature

#4829 Add missing return value names in IAccessManager
  contracts/access/manager/IAccessManager.sol
Labels: ignore-changeset

#4817 Refactor supports interface
  test/governance/Governor.test.js
  test/token/ERC1155/ERC1155.behavior.js
  test/token/ERC1155/utils/ERC1155Holder.test.js
  test/token/ERC721/ERC721.behavior.js
  test/utils/introspection/ERC165.test.js
  test/utils/introspection/SupportsInterface.behavior.js
Labels: tests, ignore-changeset

#4824 Fix gas report generation
  .github/workflows/checks.yml
  hardhat.config.js
  hardhat/env-contract.js
  package-lock.json
  package.json
  test/sanity.test.js
Labels: ignore-changeset

#4833 Remove outdated `release` script
  package.json
Labels: ignore-changeset

#4834 Run gas-compare action on push to master
  .github/workflows/checks.yml
Labels: ignore-changeset

#4838 Fix gasReport format
  scripts/checks/compareGasReports.js
Labels: ignore-changeset

#4837 Remove obsolete ERC4626 `mint` NatSpec
  contracts/token/ERC20/extensions/ERC4626.sol
Labels: ignore-changeset

#4836 Enable more solhint rules
  package-lock.json
  package.json
  solhint.config.js
Labels: ignore-changeset

#4832 Remove `hardhat-foundry` and check harnesses compilation in CI
  .github/workflows/checks.yml
  certora/harnesses/EnumerableMapHarness.sol
  certora/harnesses/EnumerableSetHarness.sol
  certora/specs/EnumerableMap.spec
  certora/specs/EnumerableSet.spec
  hardhat.config.js
  hardhat/remappings.js
  package-lock.json
  package.json
Labels: ignore-changeset

#4835 Lower fuzz runs to 5000
  foundry.toml
Labels: ignore-changeset

#4847 Remove documented requirement in IERC1155's `balanceOf`
  contracts/token/ERC1155/IERC1155.sol
Labels: ignore-changeset

#4843 Add new EnumerableMap types
  .changeset/yellow-deers-walk.md
  contracts/utils/structs/EnumerableMap.sol
  scripts/generate/templates/EnumerableMap.js
  scripts/generate/templates/EnumerableMap.opts.js
  test/helpers/random.js
  test/utils/structs/EnumerableMap.test.js
Labels: feature, Datastructures

#4848 List every contract in each API doc section
  contracts/access/README.adoc
  contracts/governance/README.adoc
  contracts/metatx/README.adoc
  contracts/utils/README.adoc
Labels: ignore-changeset

#4631 Add ERC1363 implementation
  .changeset/friendly-nails-push.md
  .changeset/nice-paws-pull.md
  contracts/interfaces/IERC1363.sol
  contracts/interfaces/IERC1363Receiver.sol
  contracts/interfaces/IERC1363Spender.sol
  contracts/mocks/token/ERC1363ForceApproveMock.sol
  contracts/mocks/token/ERC1363NoReturnMock.sol
  contracts/mocks/token/ERC1363ReceiverMock.sol
  contracts/mocks/token/ERC1363ReturnFalseMock.sol
  contracts/mocks/token/ERC1363SpenderMock.sol
  contracts/token/ERC20/README.adoc
  contracts/token/ERC20/extensions/ERC1363.sol
  contracts/token/ERC20/utils/SafeERC20.sol
  test/token/ERC20/ERC20.behavior.js
  test/token/ERC20/ERC20.test.js
  test/token/ERC20/extensions/ERC1363.test.js
  test/token/ERC20/extensions/ERC20FlashMint.test.js
  test/token/ERC20/extensions/ERC20Permit.test.js
  test/token/ERC20/extensions/ERC20Wrapper.test.js
  test/token/ERC20/utils/SafeERC20.test.js
  test/utils/introspection/SupportsInterface.behavior.js
Labels: feature, implementation-of-final-erc

#4839 Add a Math.inv function that inverse a number in Z/nZ
  .changeset/cool-mangos-compare.md
  contracts/utils/math/Math.sol
  test/utils/math/Math.t.sol
  test/utils/math/Math.test.js
Labels: feature, Cryptography

#4854 Improve ERC-1363 documentation
  contracts/token/ERC20/extensions/ERC1363.sol
Labels: documentation, ignore-changeset

#4861 Remove note about event access in `ERC1967Utils.sol`
  contracts/proxy/ERC1967/ERC1967Utils.sol
Labels: ignore-changeset

#4842 Bound lookup in arrays with duplicate
  .changeset/flat-turtles-repeat.md
  .changeset/thick-pumpkins-report.md
  contracts/mocks/ArraysMock.sol
  contracts/utils/Arrays.sol
  test/utils/Arrays.test.js
  test/utils/structs/Checkpoints.test.js
Labels: feature
