Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-02, with the labels that each got.

#4868 Remove deprecated Truffle code
  hardhat/env-artifacts.js
Labels: ignore-changeset

#4876 Fix natspec comments in ERC-1155
  contracts/token/ERC1155/IERC1155.sol
Labels: documentation, ignore-changeset

#4879 Update hardhat-exposed to remove `mock/_import.sol`
  contracts/mocks/_import.sol
  package-lock.json
  package.json
Labels: ignore-changeset, CI

#4846 Add `sort` in memory to Arrays library
  .changeset/dirty-cobras-smile.md
  contracts/utils/Arrays.sol
  scripts/generate/templates/Checkpoints.t.js
  test/utils/Arrays.t.sol
  test/utils/Arrays.test.js
  test/utils/Base64.t.sol
  test/utils/structs/Checkpoints.t.sol
Labels: feature, Datastructures

#4889 Remove gas optimization changeset entries
  .changeset/angry-dodos-grow.md
  .changeset/brown-cooks-dress.md
Labels: ignore-changeset

#4890 Fix typo in AccessManaged.sol
  contracts/access/manager/AccessManaged.sol
Labels: ignore-changeset

#4893 Add `bytes memory` version of `Math.modExp`
  .changeset/shiny-poets-whisper.md
  contracts/utils/math/Math.sol
  test/helpers/math.js
  test/utils/math/Math.t.sol
  test/utils/math/Math.test.js
Labels: ignore-changeset

#4895 Deduplicate code in `scripts/helpers` and `test/helpers/iterate`
  scripts/helpers.js
  test/helpers/governance.js
  test/helpers/iterate.js
  test/utils/math/Math.test.js
  test/utils/math/SafeCast.test.js
Labels: tests, ignore-changeset

#4403 Improved integer square root.
  contracts/utils/math/Math.sol
Labels: ignore-changeset, gas optimization

#4903 Rewrite comments using superscript for avoid confusion with xor operator
  contracts/utils/math/Math.sol
Labels: documentation, ignore-changeset

#4899 Update chai matchers
  contracts/utils/Panic.sol
  package-lock.json
  package.json
  test/utils/Panic.test.js
Labels: ignore-changeset

#4912 Simplify finance tests
  test/finance/VestingWallet.behavior.js
  test/finance/VestingWallet.test.js
  test/finance/VestingWalletCliff.test.js
Labels: tests, ignore-changeset

#4934 Update LICENSE
  LICENSE
Labels: ignore-changeset
