Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-07, with the labels that each got.

#4881 Implement P256 verification via RIP-7212 precompile with Solidity fallback
  .changeset/odd-lobsters-wash.md
  contracts/mocks/Stateless.sol
  contracts/utils/Errors.sol
  contracts/utils/README.adoc
  contracts/utils/cryptography/P256.sol
  contracts/utils/math/Math.sol
  docs/modules/ROOT/pages/utilities.adoc
  scripts/checks/coverage.sh
  test/utils/cryptography/P256.t.sol
  test/utils/cryptography/P256.test.js
  test/utils/cryptography/ecdsa_secp256r1_sha256_p1363_test.json
Labels: Cryptography

#5117 Protect Packing.pack and Packing.replace against values that include dirty bits
  contracts/utils/Packing.sol
  scripts/generate/templates/Packing.js
Labels: bug, ignore-changeset

#5115 Typographic error in Math.sol comment fix
  contracts/utils/math/Math.sol
Labels: ignore-changeset

#5121 Fix typo in Heap.sol documentation
  contracts/utils/structs/Heap.sol
  scripts/generate/templates/Heap.js
Labels: ignore-changeset

#5128 Fix documentation of private function `_upperLookupBinary` in Checkpoints.sol
  contracts/utils/structs/Checkpoints.sol
  scripts/generate/templates/Checkpoints.js
Labels: ignore-changeset

#5129 Add note about opinionated design to ERC4626Fees
  contracts/mocks/docs/ERC4626Fees.sol
Labels: ignore-changeset

#5136 Fix natspec comment missing *
  contracts/utils/structs/Heap.sol
  scripts/generate/templates/Heap.js
Labels: ignore-changeset
