Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2024-06, with the labels that each got.

#5066 Improve wording in _checkAuthorized's natspec
  contracts/token/ERC721/ERC721.sol
Labels: documentation, ignore-changeset

#5010 Update ERC1363 error signatures
  contracts/token/ERC20/extensions/ERC1363.sol
Labels: documentation, ignore-changeset

#5068 use arrays.unsafeMemoryAccess in ERC1155Supply
  contracts/token/ERC1155/extensions/ERC1155Supply.sol
Labels: ignore-changeset

#5077 Add bytes6 to the Packing library.
  contracts/utils/Packing.sol
  scripts/generate/templates/Packing.js
  scripts/generate/templates/Packing.opts.js
  scripts/generate/templates/Packing.t.js
  test/utils/Packing.t.sol
Labels: ignore-changeset

#5080 Avoid storing hashing function pointers in storage make MerkleTree structure upgrade-safe
  contracts/utils/structs/MerkleTree.sol
  docs/modules/ROOT/pages/utilities.adoc
Labels: ignore-changeset

#5069 Fix dirty bits in upper bits in implementation address in `Clones.sol`
  contracts/proxy/Clones.sol
  test/proxy/Clones.t.sol
Labels: bug, ignore-changeset

#5088 Fix repeated word in `ERC2771Forwarder` comments
  contracts/metatx/ERC2771Forwarder.sol
Labels: ignore-changeset

#5096 Fix docs links to ERC165
  contracts/utils/README.adoc
Labels: ignore-changeset

#5090 Reduce memory leakage from returndata in SafeERC20
  CHANGELOG.md
  contracts/token/ERC20/utils/SafeERC20.sol
  test/token/ERC20/utils/SafeERC20.test.js
Labels: ignore-changeset

#5100 Update LICENSE
  LICENSE
Labels: ignore-changeset

#5099 Clarify hardhat & foundry configs and enable optimisation by default.
  foundry.toml
  hardhat.config.js
Labels: ignore-changeset

#5098 Add Foundry tests to coverage
  .codecov.yml
  package.json
  scripts/checks/coverage.sh
Labels: ignore-changeset
