Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2025-02, with the labels that each got.

#5477 Fix typos and grammar in documentation
  audits/2017-03.md
Labels: ignore-changeset, typo

#5476 Fix typo in BeaconProxy.test.js
  test/proxy/beacon/BeaconProxy.test.js
Labels: ignore-changeset, typo

#5478 fix: consistent spelling: "behavior"
  contracts/proxy/Clones.sol
Labels: ignore-changeset, typo

#5481 Add forum badge correct link
  README.md
Labels: ignore-changeset

#5484 fix incorrect
  contracts/governance/extensions/GovernorTimelockAccess.sol
  contracts/utils/math/Math.sol
Labels: ignore-changeset, typo

#5488 Silent slither false positives
  contracts/utils/cryptography/EIP712.sol
  scripts/upgradeable/upgradeable.patch
Labels: ignore-changeset

#5472 Rename ERC4337Utils ENTRYPOINT to ENTRYPOINT_V07
  .changeset/chilly-guests-jam.md
  contracts/account/utils/draft-ERC4337Utils.sol
  test/account/utils/draft-ERC4337Utils.test.js
  test/account/utils/draft-ERC7579Utils.t.sol
Labels: ignore-changeset

#5493 Make set-max-old-space-size.sh compatible with sh
  scripts/set-max-old-space-size.sh
Labels: ignore-changeset, CI

#5496 Update FUNDING.json
  FUNDING.json
Labels: ignore-changeset

#5490 fix spelling issue
  contracts/governance/extensions/GovernorTimelockControl.sol
  contracts/utils/structs/Checkpoints.sol
  scripts/generate/templates/Checkpoints.js
Labels: ignore-changeset, typo

#5482 fix: Fix grammar in log message
  contracts/access/IAccessControl.sol
Labels: ignore-changeset, typo

#5500 Update FUNDING.json hierarchy
  FUNDING.json
Labels: ignore-changeset

#5499 fix grammar and spelling errors
  audits/2017-03.md
  contracts/token/ERC6909/README.adoc
  contracts/utils/structs/CircularBuffer.sol
Labels: ignore-changeset, typo

#5501 Test behavior of SignatureChecker against the identity precompile (0x4)
  test/helpers/precompiles.js
  test/utils/cryptography/SignatureChecker.test.js
Labels: ignore-changeset

#5505 spelling error
  test/token/ERC20/extensions/ERC20Wrapper.test.js
Labels: ignore-changeset, typo

#5101 Treat code-size warnings as errors
  hardhat.config.js
Labels: ignore-changeset

#5516 Fix spelling error in CHANGELOG.md
  CHANGELOG.md
Labels: ignore-changeset, typo

#5517 minor format-changelog.js
  scripts/release/format-changelog.js
Labels: ignore-changeset, typo

#5509 Release v5.3 cherrypick #1
  .changeset/gorgeous-apes-jam.md
  contracts/access/manager/AuthorityUtils.sol
  contracts/governance/TimelockController.sol
  hardhat.config.js
  test/helpers/precompiles.js
  test/utils/cryptography/SignatureChecker.test.js
  test/utils/math/Math.t.sol
Labels: release-cycle, cherrypick

#5519 Add Arachnid's and Micah's deployer to the common contracts
  hardhat/common-contracts.js
Labels: tests, ignore-changeset

#5525 Fix spelling errors in `GUIDELINES.md` and `README.adoc`
  GUIDELINES.md
  contracts/utils/README.adoc
Labels: ignore-changeset, typo

#5510 chore: fix incorrect
  contracts/utils/TransientSlot.sol
  scripts/generate/templates/Checkpoints.t.js
  scripts/generate/templates/TransientSlot.js
  test/access/AccessControl.behavior.js
  test/utils/structs/Checkpoints.t.sol
Labels: ignore-changeset, typo

#5316 Fix: Ensure cross-platform compatibility for sed command in CI script
  scripts/checks/coverage.sh
Labels: ignore-changeset

#5081 `MessageHashUtils`: Add `toDataWithIntendedValidatorHash(address, bytes32)`
  .changeset/quiet-shrimps-kiss.md
  contracts/utils/cryptography/MessageHashUtils.sol
  test/utils/cryptography/MessageHashUtils.t.sol
  test/utils/cryptography/MessageHashUtils.test.js
Labels: idea
