Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2025-09, with the labels that each got.

#5895 chore: fix typos and clarify role naming
  test/access/AccessControl.behavior.js
  test/access/manager/AccessManager.behavior.js
  test/account/utils/draft-ERC7579Utils.t.sol
Labels: ignore-changeset, typo

#5909 docs: fix grammar and clarity in documentation
  docs/modules/ROOT/pages/access-control.adoc
  docs/modules/ROOT/pages/erc4626.adoc
  docs/modules/ROOT/pages/governance.adoc
  docs/modules/ROOT/pages/utilities.adoc
Labels: ignore-changeset, typo

#5916 docs: fix incorrect ERC standard references and URL formatting
  contracts/interfaces/draft-IERC6093.sol
Labels: ignore-changeset, typo

#5927 fix: remove duplicate `shares` in IERC4626 function documentation
  contracts/interfaces/IERC4626.sol
Labels: ignore-changeset, typo

#5932 Rename SignerERC7702 as SignerEIP7702
  CHANGELOG.md
  contracts/mocks/account/AccountMock.sol
  contracts/mocks/docs/account/MyAccountERC7702.sol
  contracts/utils/cryptography/README.adoc
  contracts/utils/cryptography/signers/SignerEIP7702.sol
  docs/modules/ROOT/pages/accounts.adoc
  docs/modules/ROOT/pages/eoa-delegation.adoc
Labels: breaking change, ignore-changeset

#5943 docs: fix some typos
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC20/extensions/ERC4626.sol
  contracts/token/ERC20/extensions/IERC20Permit.sol
  contracts/token/ERC20/utils/SafeERC20.sol
Labels: ignore-changeset, typo

#5942 Mark ERC721Holder and ERC1155Holder as stateless
  CHANGELOG.md
  contracts/token/ERC1155/utils/ERC1155Holder.sol
  contracts/token/ERC721/utils/ERC721Holder.sol
Labels: breaking change, ignore-changeset, area: upgradeability

#5877 Use the "dev" tag for new releases
  scripts/release/workflow/pack.sh
Labels: ignore-changeset, release-cycle

#5944 ReentrancyGuard & ReentrancyGuardTransient are stateless
  CHANGELOG.md
  contracts/utils/ReentrancyGuard.sol
  contracts/utils/ReentrancyGuardTransient.sol
  scripts/upgradeable/upgradeable.patch
Labels: breaking change, ignore-changeset, area: upgradeability

#5934 Clarify AccessControl vs AccessControlEnumerable role enumeration
  docs/modules/ROOT/pages/access-control.adoc
Labels: documentation, ignore-changeset

#5532 Refactor and fix async operations in ERC2771Context.test.js
  test/metatx/ERC2771Context.test.js
Labels: tests, ignore-changeset

#5951 docs: fix typos
  contracts/proxy/transparent/TransparentUpgradeableProxy.sol
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC20/utils/SafeERC20.sol
Labels: ignore-changeset, typo

#5955 fix: incorrect documentation reference in ERC4626Fees._withdraw
  contracts/mocks/docs/ERC4626Fees.sol
Labels: ignore-changeset, typo
