Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2025-07, with the labels that each got.

#5774 chore: remove redundant word
  contracts/utils/cryptography/draft-ERC7739Utils.sol
Labels: ignore-changeset

#5777 Fix typos in release-5.4
  contracts/utils/cryptography/signers/MultiSignerERC7913.sol
  contracts/utils/structs/EnumerableMap.sol
  scripts/generate/templates/EnumerableMap.js
Labels: ignore-changeset, typo

#5776 Improve naming consystency in EnumerableSet
  contracts/utils/structs/EnumerableSet.sol
  scripts/generate/templates/EnumerableSet.js
Labels: ignore-changeset

#5783 Fix flaky test `testFuzzFutureBlocks`
  test/utils/Blockhash.t.sol
Labels: ignore-changeset

#5790 Cause _addSigners to revert if it triggers a totalWeight overflow
  contracts/utils/cryptography/signers/MultiSignerERC7913Weighted.sol
  test/account/AccountMultiSignerWeighted.test.js
Labels: ignore-changeset

#5788 Add Calldata variants of ECDSA.recover, ECDSA.tryRecover and SignatureChecker.isValidSignatureNow
  .changeset/violet-turtles-like.md
  .changeset/whole-plums-speak.md
  contracts/utils/cryptography/ECDSA.sol
  contracts/utils/cryptography/SignatureChecker.sol
  test/utils/cryptography/ECDSA.test.js
  test/utils/cryptography/SignatureChecker.test.js
Labels: gas optimization, OIF

#5796 Explicit Initialization of Loop Counter in escapeJSON Function
  contracts/utils/Strings.sol
Labels: ignore-changeset

#5771 Refactor SafeERC20 to save gas
  contracts/token/ERC20/utils/SafeERC20.sol
Labels: ignore-changeset, gas optimization, OIF

#5797 Fix bug in Bytes.lastIndexOf when array is empty and position is not 2²⁵⁶-1
  .changeset/witty-hats-flow.md
  contracts/utils/Bytes.sol
  test/utils/Bytes.t.sol
  test/utils/Bytes.test.js
Labels: bug

#5799 Add audit report for v5.4
  audits/2025-07-v5.4.pdf
  audits/README.md
Labels: ignore-changeset

#5726 Add `equal` to Bytes.sol and update pragma to 0.8.24 in String dependencies
  .changeset/ten-steaks-try.md
  CHANGELOG.md
  contracts/governance/utils/Votes.sol
  contracts/governance/utils/VotesExtended.sol
  contracts/metatx/ERC2771Forwarder.sol
  contracts/mocks/EIP712Verifier.sol
  contracts/mocks/VotesExtendedMock.sol
  contracts/mocks/VotesMock.sol
  contracts/mocks/docs/MyNFT.sol
  contracts/mocks/docs/governance/MyToken.sol
  contracts/mocks/docs/governance/MyTokenTimestampBased.sol
  contracts/mocks/docs/governance/MyTokenWrapped.sol
  contracts/mocks/docs/token/ERC721/GameItem.sol
  contracts/mocks/docs/utilities/Base64NFT.sol
  contracts/mocks/token/ERC20VotesAdditionalCheckpointsMock.sol
  contracts/mocks/token/ERC20VotesLegacyMock.sol
  contracts/mocks/token/ERC20VotesTimestampMock.sol
  contracts/mocks/token/ERC721ConsecutiveEnumerableMock.sol
  contracts/mocks/token/ERC721ConsecutiveMock.sol
  contracts/mocks/token/ERC721URIStorageMock.sol
  contracts/mocks/utils/cryptography/ERC7739Mock.sol
  contracts/token/ERC1155/extensions/ERC1155URIStorage.sol
  contracts/token/ERC20/extensions/ERC20Permit.sol
  contracts/token/ERC20/extensions/ERC20Votes.sol
  contracts/token/ERC721/ERC721.sol
  contracts/token/ERC721/extensions/ERC721Burnable.sol
  contracts/token/ERC721/extensions/ERC721Consecutive.sol
  contracts/token/ERC721/extensions/ERC721Enumerable.sol
  contracts/token/ERC721/extensions/ERC721Pausable.sol
  contracts/token/ERC721/extensions/ERC721Royalty.sol
  contracts/token/ERC721/extensions/ERC721URIStorage.sol
  contracts/token/ERC721/extensions/ERC721Votes.sol
  contracts/token/ERC721/extensions/ERC721Wrapper.sol
  contracts/utils/Bytes.sol
  contracts/utils/Strings.sol
  contracts/utils/cryptography/EIP712.sol
  contracts/utils/cryptography/MessageHashUtils.sol
  contracts/utils/cryptography/signers/draft-ERC7739.sol
  test/utils/Bytes.t.sol
Labels: ignore-changeset

#5813 Update Math.sol (Fixes typo in NatSpec)
  contracts/utils/math/Math.sol
Labels: ignore-changeset, typo
