Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2025-01, with the labels that each got.

#5410 Make IERC7579Execution payable
  contracts/interfaces/draft-IERC7579.sol
Labels: ignore-changeset

#5417 Update ReentrancyGuardTransient documentation
  contracts/utils/ReentrancyGuardTransient.sol
Labels: ignore-changeset

#5415 Optimize `MerkleTree` for loops by using `uint256` iterators
  contracts/utils/structs/MerkleTree.sol
Labels: ignore-changeset

#5321 Update `_revokeRole` documentation in AccessControl
  contracts/access/AccessControl.sol
Labels: ignore-changeset

#5420 Update governor docs
  contracts/governance/README.adoc
Labels: ignore-changeset

#5428 Add missing `Calldata`, `Bytes`, `CAIP2` and `CAIP10` API references
  contracts/utils/README.adoc
Labels: documentation, ignore-changeset

#5441 Refactor EnumerableSet.behavior.js for reuse in the community repo
  test/utils/structs/EnumerableSet.behavior.js
Labels: ignore-changeset

#5438 fix typos
  README.md
  RELEASING.md
  certora/specs/AccessControlDefaultAdminRules.spec
Labels: ignore-changeset

#5402 Fix Typographical Errors in Contracts and Tests
  contracts/token/common/ERC2981.sol
  contracts/utils/Arrays.sol
  scripts/generate/templates/Arrays.js
  test/metatx/ERC2771Forwarder.t.sol
Labels: ignore-changeset

#5435 Remove extraneous word in `governance.adoc`
  docs/modules/ROOT/pages/governance.adoc
Labels: ignore-changeset

#5446 Replace `overriden` with `overridden` in GovernorCountingOverridable.sol
  CHANGELOG.md
  contracts/governance/extensions/GovernorCountingOverridable.sol
  test/governance/extensions/GovernorCountingOverridable.test.js
Labels: ignore-changeset

#5436 Fix Broken Docs References
  .gitignore
  contracts/governance/Governor.sol
  contracts/governance/README.adoc
  contracts/governance/extensions/GovernorStorage.sol
  contracts/governance/extensions/GovernorTimelockAccess.sol
  contracts/proxy/utils/UUPSUpgradeable.sol
  contracts/token/ERC1155/IERC1155.sol
  contracts/token/ERC1155/utils/ERC1155Utils.sol
  contracts/token/ERC20/extensions/ERC4626.sol
  contracts/token/ERC721/extensions/ERC721Consecutive.sol
  contracts/token/ERC721/extensions/ERC721URIStorage.sol
  contracts/token/ERC721/utils/ERC721Utils.sol
  contracts/utils/Multicall.sol
  contracts/utils/ShortStrings.sol
  contracts/utils/Strings.sol
  contracts/utils/cryptography/EIP712.sol
  docs/modules/ROOT/pages/crowdsales.adoc
  docs/modules/ROOT/pages/drafts.adoc
  docs/modules/ROOT/pages/governance.adoc
  docs/templates/contract.hbs
  docs/templates/properties.js
Labels: documentation, ignore-changeset

#5456 Remove unused `setBaseURI` tests
  test/token/ERC721/ERC721.behavior.js
Labels: ignore-changeset

#5443 Group typographical errors
  CHANGELOG.md
  README.md
  RELEASING.md
  SECURITY.md
  audits/2017-03.md
  certora/README.md
  certora/specs/AccessControlDefaultAdminRules.spec
  certora/specs/ERC20FlashMint.spec
  contracts/finance/VestingWallet.sol
  contracts/governance/extensions/GovernorCountingFractional.sol
  contracts/interfaces/IERC1271.sol
  contracts/token/ERC721/README.adoc
  contracts/token/common/ERC2981.sol
  contracts/utils/Arrays.sol
  docs/modules/ROOT/pages/erc20-supply.adoc
  docs/modules/ROOT/pages/governance.adoc
  scripts/generate/templates/Arrays.js
  test/metatx/ERC2771Forwarder.t.sol
Labels: ignore-changeset

#5458 fix correction
  contracts/interfaces/IERC4626.sol
  contracts/proxy/utils/Initializable.sol
Labels: ignore-changeset, typo

#5460 Fix interface docs ordering and add missing interface
  contracts/interfaces/README.adoc
Labels: ignore-changeset

#5303 Add a governor extension that implements a proposal guardian
  .changeset/pretty-lobsters-tan.md
  contracts/governance/Governor.sol
  contracts/governance/IGovernor.sol
  contracts/governance/README.adoc
  contracts/governance/extensions/GovernorProposalGuardian.sol
  contracts/mocks/governance/GovernorProposalGuardianMock.sol
  test/governance/Governor.test.js
  test/governance/extensions/GovernorProposalGuardian.test.js
Labels: area: governance

#5445 Fix the CLI output of formal verification runs
  certora/run.js
Labels: ignore-changeset

#5465 Use stable foundry version in CI
  .github/actions/setup/action.yml
Labels: ignore-changeset

#5462 Add missing apostrophe `owner` s to `owner`'s
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC20/extensions/draft-ERC20TemporaryApproval.sol
Labels: ignore-changeset
