Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2025-08, with the labels that each got.

#5839 fix: remove duplicate word in ERC7821 comment
  contracts/account/extensions/draft-ERC7821.sol
Labels: ignore-changeset

#5857 polishing docs: error fixes for clarity
  contracts/access/manager/IAccessManager.sol
  contracts/account/utils/EIP7702Utils.sol
Labels: ignore-changeset

#5812 Remove OpenZeppelin Defender link from README.md
  README.md
Labels: documentation, ignore-changeset

#5864 Disable foundry lint-on-build to fix CI
  foundry.toml
Labels: ignore-changeset, CI

#5860 docs(ERC20): link ERC20Votes to governance guide minimal example
  contracts/token/ERC20/README.adoc
Labels: documentation, ignore-changeset

#5867 Rewrite assertion chains
  test/account/AccountMultiSigner.test.js
  test/token/ERC20/ERC20.behavior.js
Labels: ignore-changeset

#5871 fix(imports): correct IERC165 import path
  contracts/access/extensions/AccessControlDefaultAdminRules.sol
Labels: ignore-changeset

#5872 Formal verification of Account (7702+7579)
  certora/diff/account_extensions_draft-AccountERC7579.sol.patch
  certora/harnesses/AccountHarness.sol
  certora/specs/Account.conf
  certora/specs/Account.spec
  certora/specs/methods/IAccount.spec
Labels: ignore-changeset, formal-verification, Account Abstraction

#5875 docs: fix typos and grammar in Solidity source comments
  contracts/token/ERC721/extensions/ERC721Consecutive.sol
  contracts/token/ERC721/utils/ERC721Utils.sol
  contracts/utils/Bytes.sol
  contracts/utils/draft-InteroperableAddress.sol
  contracts/utils/structs/CircularBuffer.sol
  contracts/utils/types/Time.sol
Labels: ignore-changeset

#5879 docs: fix typos and grammar in comments
  contracts/access/extensions/AccessControlDefaultAdminRules.sol
  contracts/access/manager/AccessManager.sol
  contracts/metatx/ERC2771Context.sol
  contracts/mocks/docs/ERC4626Fees.sol
Labels: ignore-changeset, typo

#5883 Update IERC7786 to match latest ERC changes
  contracts/interfaces/draft-IERC7786.sol
Labels: ignore-changeset
