Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2025-03, with the labels that each got.

#5466 Group typo fixes
  .changeset/brown-turkeys-marry.md
  .github/actions/gas-compare/action.yml
  .github/workflows/checks.yml
  CHANGELOG.md
  GUIDELINES.md
  RELEASING.md
  audits/2017-03.md
  contracts/access/IAccessControl.sol
  contracts/governance/extensions/GovernorTimelockControl.sol
  contracts/interfaces/IERC4626.sol
  contracts/proxy/Clones.sol
  contracts/proxy/utils/Initializable.sol
  contracts/token/ERC20/ERC20.sol
  contracts/token/ERC20/extensions/draft-ERC20TemporaryApproval.sol
  contracts/token/ERC6909/README.adoc
  contracts/utils/README.adoc
  contracts/utils/SlotDerivation.sol
  contracts/utils/TransientSlot.sol
  contracts/utils/math/Math.sol
  contracts/utils/structs/Checkpoints.sol
  contracts/utils/structs/CircularBuffer.sol
  scripts/generate/templates/Checkpoints.js
  scripts/generate/templates/Checkpoints.t.js
  scripts/generate/templates/SlotDerivation.js
  scripts/generate/templates/TransientSlot.js
  scripts/release/format-changelog.js
  test/access/AccessControl.behavior.js
  test/account/utils/draft-ERC7579Utils.t.sol
  test/metatx/ERC2771Context.test.js
  test/proxy/beacon/BeaconProxy.test.js
  test/token/ERC20/extensions/ERC20Wrapper.test.js
  test/token/ERC6909/ERC6909.behavior.js
  test/token/ERC6909/extensions/ERC6909ContentURI.test.js
  test/utils/structs/Checkpoints.t.sol
Labels: ignore-changeset, typo

#5547 spelling errors
  contracts/mocks/docs/access-control/AccessControlModified.sol
  contracts/mocks/token/ERC20ForceApproveMock.sol
Labels: ignore-changeset, typo

#5553 Improve clarity in utilities.adoc
  docs/modules/ROOT/pages/utilities.adoc
Labels: ignore-changeset, typo

#5575 spelling issues
  contracts/utils/TransientSlot.sol
  test/governance/extensions/GovernorVotesSuperQuorumFraction.test.js
Labels: ignore-changeset

#5576 fix spelling issues ERC4626.test.js
  test/token/ERC20/extensions/ERC4626.test.js
Labels: ignore-changeset, typo

#5581 Improve error granularity of EnumerableMap behavior tests
  test/utils/structs/EnumerableMap.behavior.js
Labels: tests, ignore-changeset

#5572 Release v5.3 cherrypick #3
  .changeset/lucky-teachers-sip.md
  contracts/utils/structs/EnumerableSet.sol
  scripts/generate/templates/EnumerableSet.js
  scripts/generate/templates/EnumerableSet.opts.js
  test/utils/structs/EnumerableSet.test.js
Labels: ignore-changeset

#5586 Use Entrypoint's provided hashing function to support v0.8.0 change of hash
  contracts/account/utils/draft-ERC4337Utils.sol
  hardhat/common-contracts.js
  scripts/fetch-common-contracts.js
  test/account/utils/draft-ERC4337Utils.test.js
  test/account/utils/draft-ERC7579Utils.t.sol
  test/bin/EntryPoint080.abi
  test/bin/EntryPoint080.bytecode
  test/bin/SenderCreator080.abi
  test/bin/SenderCreator080.bytecode
  test/helpers/erc4337.js
Labels: ignore-changeset, Account Abstraction

#5605 Cherrypick 0a77e54c307d9becf0473b73541c4f9d3b2743a3 onto release-v5.3
  contracts/account/utils/draft-ERC4337Utils.sol
  hardhat/common-contracts.js
  scripts/fetch-common-contracts.js
  test/account/utils/draft-ERC4337Utils.test.js
  test/account/utils/draft-ERC7579Utils.t.sol
  test/bin/EntryPoint080.abi
  test/bin/EntryPoint080.bytecode
  test/bin/SenderCreator080.abi
  test/bin/SenderCreator080.bytecode
  test/helpers/erc4337.js
Labels: ignore-changeset

#5590 `ERC2771Context` gas improvements
  contracts/metatx/ERC2771Context.sol
Labels: ignore-changeset, gas optimization

#5602 Implement ERC-7821 calldata compression in ERC7579Utils
  contracts/account/utils/draft-ERC7579Utils.sol
  test/account/utils/draft-ERC7579Utils.test.js
Labels: ignore-changeset, Account Abstraction

#5610 Cherrypick #5602 onto release-v5.3
  contracts/account/utils/draft-ERC7579Utils.sol
  test/account/utils/draft-ERC7579Utils.test.js
Labels: ignore-changeset
