Repository OpenZeppelin/openzeppelin-contracts, pull requests merged in 2025-06, with the labels that each got.

#5587 Add EIP7702Utils
  .changeset/full-ways-help.md
  contracts/account/utils/EIP7702Utils.sol
  contracts/mocks/Stateless.sol
  test/account/utils/EIP7702Utils.test.js
Labels: Account Abstraction

#5657 Add Account framework
  .changeset/clean-ways-push.md
  .changeset/funny-years-yawn.md
  .changeset/lazy-poets-cheer.md
  .changeset/rotten-apes-lie.md
  .changeset/strong-points-change.md
  .changeset/tame-bears-mix.md
  contracts/account/Account.sol
  contracts/account/README.adoc
  contracts/account/extensions/AccountERC7579.sol
  contracts/account/extensions/AccountERC7579Hooked.sol
  contracts/account/extensions/ERC7821.sol
  contracts/interfaces/IERC7821.sol
  contracts/mocks/CallReceiverMock.sol
  contracts/mocks/account/AccountMock.sol
  contracts/mocks/account/modules/ERC7579Mock.sol
  contracts/mocks/utils/cryptography/ERC7739Mock.sol
  contracts/utils/README.adoc
  contracts/utils/cryptography/SignerECDSA.sol
  contracts/utils/cryptography/SignerERC7702.sol
  contracts/utils/cryptography/SignerP256.sol
  contracts/utils/cryptography/SignerRSA.sol
  scripts/upgradeable/upgradeable.patch
  test/account/Account.behavior.js
  test/account/Account.test.js
  test/account/AccountECDSA.test.js
  test/account/AccountERC7702.t.sol
  test/account/AccountERC7702.test.js
  test/account/AccountP256.test.js
  test/account/AccountRSA.test.js
  test/account/examples/AccountERC7702WithModulesMock.test.js
  test/account/extensions/AccountERC7579.behavior.js
  test/account/extensions/AccountERC7579.test.js
  test/account/extensions/AccountERC7579Hooked.test.js
  test/account/extensions/ERC7821.behavior.js
  test/helpers/eip712-types.js
  test/helpers/erc4337.js
  test/helpers/signers.js
  test/utils/cryptography/ERC7739.test.js
Labels: Account Abstraction, migration from community

#5711 Reorder cryptography folder
  contracts/account/Account.sol
  contracts/mocks/account/AccountMock.sol
  contracts/mocks/utils/cryptography/ERC7739Mock.sol
  contracts/utils/README.adoc
  contracts/utils/cryptography/README.adoc
  contracts/utils/cryptography/signers/AbstractSigner.sol
  contracts/utils/cryptography/signers/ERC7739.sol
  contracts/utils/cryptography/signers/SignerECDSA.sol
  contracts/utils/cryptography/signers/SignerERC7702.sol
  contracts/utils/cryptography/signers/SignerP256.sol
  contracts/utils/cryptography/signers/SignerRSA.sol
  scripts/gen-nav.js
Labels: ignore-changeset

#5713 Add paginated version of EnumerableSet.values() and EnumerableMap.keys()
  .changeset/fine-frogs-bake.md
  .changeset/hot-grapes-lie.md
  contracts/utils/structs/EnumerableMap.sol
  contracts/utils/structs/EnumerableSet.sol
  scripts/generate/templates/EnumerableMap.js
  scripts/generate/templates/EnumerableSet.js
  test/utils/structs/EnumerableMap.behavior.js
  test/utils/structs/EnumerableMap.test.js
  test/utils/structs/EnumerableSet.behavior.js
  test/utils/structs/EnumerableSet.test.js
Labels: Datastructures

#5717 Fix docs references to cryptographic utilities
  contracts/utils/cryptography/ERC7739Utils.sol
  contracts/utils/cryptography/signers/AbstractSigner.sol
  contracts/utils/cryptography/signers/ERC7739.sol
  contracts/utils/cryptography/signers/SignerECDSA.sol
  contracts/utils/cryptography/signers/SignerP256.sol
  contracts/utils/cryptography/signers/SignerRSA.sol
  docs/modules/ROOT/pages/utilities.adoc
Labels: ignore-changeset

#5719 Rename isValidERC7913SignatureNow to isValidSignatureNow
  contracts/utils/cryptography/SignatureChecker.sol
  contracts/utils/cryptography/signers/MultiSignerERC7913.sol
  contracts/utils/cryptography/signers/SignerERC7913.sol
  docs/modules/ROOT/pages/utilities.adoc
  test/utils/cryptography/SignatureChecker.test.js
Labels: ignore-changeset

#5720 Update language in legal disclaimer
  SECURITY.md
Labels: documentation, ignore-changeset

#5732 Improve test of Blockhash.sol: all cases on supported and unsupported chains
  test/utils/Blockhash.test.js
Labels: tests, ignore-changeset

#5742 Add draft- prefix to ERC-7821
  contracts/account/extensions/draft-ERC7821.sol
  contracts/interfaces/draft-IERC7821.sol
  contracts/mocks/account/AccountMock.sol
  test/account/AccountERC7702.t.sol
Labels: ignore-changeset

#5743 Add draft- prefix to ERC-7821 (#5742)
  contracts/account/extensions/draft-ERC7821.sol
  contracts/interfaces/draft-IERC7821.sol
  contracts/mocks/account/AccountMock.sol
  test/account/AccountERC7702.t.sol
Labels: ignore-changeset

#5749 Add Codeowners
  .github/CODEOWNERS
Labels: ignore-changeset

#5754 Fix upgradeable workflow by not running the linter on transpiled output
  scripts/upgradeable/transpile-onto.sh
Labels: automation, ignore-changeset, CI

#5748 Add checkpoint variant with uint256 keys and values
  .changeset/eight-radios-check.md
  contracts/utils/structs/Checkpoints.sol
  scripts/generate/templates/Checkpoints.js
  scripts/generate/templates/Checkpoints.opts.js
  scripts/generate/templates/Checkpoints.t.js
  test/utils/structs/Checkpoints.t.sol
  test/utils/structs/Checkpoints.test.js
Labels: Datastructures

#5740 Add script to automatically minimize pragma
  contracts/mocks/DummyImplementation.sol
  contracts/mocks/account/AccountMock.sol
  package.json
  scripts/minimize-pragma.js
Labels: tooling, ignore-changeset

#5752 Update hardhat and hardhat-ethers dependencies
  package-lock.json
  package.json
Labels: ignore-changeset

#5772 MultiSignerERC7913: prevent setting the threshold to zero
  contracts/utils/cryptography/signers/MultiSignerERC7913.sol
  test/account/AccountMultiSigner.test.js
Labels: ignore-changeset
